### ISSUE TITLE
Python3.5.1 => RuntimeError: The 'apxs' command appears not to be installed or is not executable

### ISSUE THREAD

**Issue by OdeyaMartin** [GrahamDumpleton/mod_wsgi#136]
Hi
I am trying to install mod_wsgi on Django but, hit the bump in the road.
Pls tell how should I be resolving problem.

System info:
Apache2.4.6 + Django1.9.6 + Python3.5.1 + Centos 7

Issue:
```
[root@localhost httpd]# pip3 install https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip'
Collecting https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip
  Downloading https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip (761kB)
    100% |████████████████████████████████| 768kB 342kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-iob9elmq-build/setup.py", line 139, in <module>
        'missing Apache httpd server packages.' % APXS)
    RuntimeError: The 'apxs' command appears not to be installed or is not executable. Please check the list of prerequisites in the documentation for this package and install any missing Apache httpd server packages.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-iob9elmq-build/
```

**Comment by GrahamDumpleton** [comment]
You need to install the 'dev' or 'devel' variant of the Apache package for your operating system. This is detailed on the PyPi page for mod_wsgi. For CentOS, from memory the package is called ``httpd-devel``.

**Comment by OdeyaMartin** [comment]
Humm...i am having any problem again.
i have just installed httpd-devel .
```
[root@localhost httpd]# yum install httpd-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
.
.
Installed:
  httpd-devel.x86_64 0:2.4.6-40.el7.centos.1

Dependency Installed:
  apr-devel.x86_64 0:1.4.8-3.el7              apr-util-devel.x86_64 0:1.5.2-6.el7      cyrus-sasl.x86_64 0:2.1.26-20.el7_2      cyrus-sasl-devel.x86_64 0:2.1.26-20.el7_2      libdb-devel.x86_64 0:5.3.21-19.el7
  openldap-devel.x86_64 0:2.4.40-9.el7_2

Complete!
```
but another problem is occuring.
Pls help me again. 

Next Issue :
```
[root@localhost httpd]# pip3 install mod_wsgi
Collecting mod_wsgi
  Using cached mod_wsgi-4.5.2.tar.gz
Installing collected packages: mod-wsgi
  Running setup.py install for mod-wsgi ... error
    Complete output from command /usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lqhu4xal/mod-wsgi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-up95rl8h-record/install-record.txt --single-version-externally-managed --compile:
.
.
.
.
.
.
gcc -pthread -shared -Wl,-rpath /usr/local/lib build/temp.linux-x86_64-3.5/src/server/mod_wsgi.o build/temp.linux-x86_64-3.5/src/server/wsgi_apache.o build/temp.linux-x86_64-3.5/src/server/wsgi_buckets.o build/temp.linux-x86_64-3.5/src/server/wsgi_convert.o build/temp.linux-x86_64-3.5/src/server/wsgi_daemon.o build/temp.linux-x86_64-3.5/src/server/wsgi_interp.o build/temp.linux-x86_64-3.5/src/server/wsgi_logger.o build/temp.linux-x86_64-3.5/src/server/wsgi_memory.o build/temp.linux-x86_64-3.5/src/server/wsgi_metrics.o build/temp.linux-x86_64-3.5/src/server/wsgi_restrict.o build/temp.linux-x86_64-3.5/src/server/wsgi_server.o build/temp.linux-x86_64-3.5/src/server/wsgi_stream.o build/temp.linux-x86_64-3.5/src/server/wsgi_thread.o build/temp.linux-x86_64-3.5/src/server/wsgi_validate.o -o build/lib.linux-x86_64-3.5/mod_wsgi/server/mod_wsgi-py35.cpython-35m-x86_64-linux-gnu.so -L/usr/local/lib -L/usr/local/lib/python3.5/config-3.5m -lpython3.5m
    /usr/bin/ld: /usr/local/lib/libpython3.5m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
    /usr/local/lib/libpython3.5m.a: could not read symbols: Bad value
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lqhu4xal/mod-wsgi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-up95rl8h-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-lqhu4xal/mod-wsgi/
```

**Comment by GrahamDumpleton** [comment]
Your Python installation was not configured with ``--enable-shared`` when it was built. You will need to reinstall the Python installation. See:

* http://blog.dscpl.com.au/2015/06/installing-custom-python-version-into.html

Ignore that talks about Docker, still gives details you need.

**Comment by OdeyaMartin** [comment]
Thank you for your help.

**Comment by GrahamDumpleton** [comment]
Assuming this is now solved. Closing.

**Comment by siempay** [comment]
Im having the same problem but I cant even install that httpd-devel

`[root@server ~]# yum install httpd-devel
Modules complémentaires chargés : fastestmirror, universal-hooks
Loading mirror speeds from cached hostfile
 * EA4: 91.197.228.252
 * base: mirror.daniel-jost.net
 * epel: mirrors.n-ix.net
 * extras: mirror.daniel-jost.net
 * updates: mirror.daniel-jost.net
 * webtatic: uk.repo.webtatic.com
Aucun paquet httpd-devel disponible.
Erreur : Rien à faire`

**Comment by GrahamDumpleton** [comment]
Not sure how to help with that one. Suggests an issue with what package repositories your operating system is looking at. What version of RHEL or CentOS are you running?

**Comment by siempay** [comment]
I've fixed it, I was that yum was excluding any httpd* , mysql* thing etc cause these were managed by other programs so yum don't want to miss with these, so what i did is I went to yum config and comment out that line the one that excluding httpd* and than run yum install httpd-devel and it worked fin

**Comment by GammaGames** [comment]
If anyone finds this thread by googling the error message and is on Alpine, the equivalent package is `apache2-dev`. You will also need the `build-base` package for `gcc`.

**Comment by Rasmis** [comment]
> If anyone finds this thread by googling the error message and is on Alpine, the equivalent package is `apache2-dev`. You will also need the `build-base` package for `gcc`.

Same on Debian. `apache2-dev`
