### ISSUE TITLE
Support Python 3.6 with Visual C++ 14.0

### ISSUE THREAD

**Issue by andrei-ivanov** [GrahamDumpleton/mod_wsgi#188]
Hi,
Seeing that there are no more binaries provided for Windows, I started reading the compilation section and I noticed in the 4.5.14 release folder that the latest supported Python and compiler is ap24py34-win64-VC10.mk.

My Python version is 3.6, which seems to be compiled with Visual C++ 14.0, same as the latest Apache Httpd provided by ApacheLounge.

Please support this combination too.

Thank you

**Comment by GrahamDumpleton** [comment]
The ``win32`` directory is no longer used and needs to be removed.

The better way of installing for Windows is to ensure you have ``pip`` and can install Python packages which have C extension components that need a compiler.

Ensure you have Apache 2.4 under ``C:\Apache24``, or set ``MOD_WSGI_APACHE_ROOTDIR`` environment variable to where it is located, then run:

```
pip install mod_wsgi
```

Then run:

```
mod_wsgi-express module-config
```

That will generate the configuration you need to add to Apache configuration file to load mod_wsgi.

Then add configuration for your specific WSGI application.

**Comment by andrei-ivanov** [comment]
Hi,
The pip part went well, the 2nd, not so well :-(
```
C:\>mod_wsgi-express module-config
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\mod_wsgi-express-script.py", line 11, in <module>
    load_entry_point('mod-wsgi==4.5.14', 'console_scripts', 'mod_wsgi-express')()
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\program files\python36\lib\site-packages\mod_wsgi\server\__init__.py", line 24, in <module>
    from . import apxs_config
  File "c:\program files\python36\lib\site-packages\mod_wsgi\server\apxs_config.py", line 27
    LIBEXECDIR = 'c:\Users\me\Apps\httpd/lib'
                    ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

This is with _MOD_WSGI_APACHE_ROOTDIR=c:\Users\me\Apps\httpd_

I ran pip uninstall and then changed the path to use / instead of \ and it worked that way.

**Comment by GrahamDumpleton** [comment]
Probably right. Can never remember which path convention meant to use. :-)
