### ISSUE TITLE
Unable to restart application after upgrade to latest Django and modwsgi

### ISSUE THREAD

**Issue by DanBuchan** [GrahamDumpleton/mod_wsgi#193]
Currently pip freeze reports:
```
Django==1.10.5
mod-wsgi==4.4.21
mod-wsgi-httpd==2.4.12.6
```

I'm starting my django app with the following
```
python manage.py runmodwsgi --settings=analytics_automated_project.settings.staging --setup-only --user django_aa --group apache --threads=10 --processes=4 --reload-on-changes --server-root=/opt/aa_httpd
```

Which returns the following error
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/django_aa/aa_env/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/django_aa/aa_env/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/django_aa/aa_env/lib/python3.4/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/django_aa/aa_env/lib/python3.4/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/django_aa/aa_env/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/django_aa/aa_env/lib/python3.4/site-packages/mod_wsgi/server/management/commands/runmodwsgi.py", line 9, in <module>
    class Command(BaseCommand):
  File "/home/django_aa/aa_env/lib/python3.4/site-packages/mod_wsgi/server/management/commands/runmodwsgi.py", line 10, in Command
    option_list = BaseCommand.option_list + mod_wsgi.server.option_list
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

Judging by other info I'd found online I had assumed that this was fixed in modwsgi 4.4.15. Is there something else I'm missing?

**Comment by DanBuchan** [comment]
For now I've monkey patched the changes in `https://github.com/GrahamDumpleton/mod_wsgi/archive/develop.zip` in to my mod-wsgi 4.4.21install. Which works but is moderately unsatisfying

**Comment by GrahamDumpleton** [comment]
Did you mean to say 4.5.15 instead of 4.4.15?

**Comment by DanBuchan** [comment]
Sorry have been busy,

It seems the pip on my server grabbed an old mod_wsgi for some yet to be diagnosed reason. There isn't an issue here now.
