### ISSUE TITLE
mod_wsgi-express doesn't have start-server command

### ISSUE THREAD

**Issue by Moataz-E** [GrahamDumpleton/mod_wsgi#210]
Hi,

I've installed mod_wsgi with Anaconda Python 3.4.5. The installation went fine but when I try to run the mod_wsgi-express script it only takes in two commands and doesn't support any other command:

>mod_wsgi-express

Usage: mod_wsgi-express command [params]

Commands:
    module-config
    module-location

mod_wsgi-express: error: No command was specified.

>mod_wsgi-express start-server

Usage: mod_wsgi-express command [params]

Commands:
    module-config
    module-location

mod_wsgi-express: error: Invalid command was specified.

**Comment by GrahamDumpleton** [comment]
On Windows the ``start-server`` command is not available. Using ``pip install mod_wsgi`` on Windows is only for getting the ``mod_wsgi`` module compiled. Once you have it compiled, run:

```
mod_wsgi-express module-config
```

Copy the output from that into your Apache configuration file to have it load the ``mod_wsgi`` module. Then configure Apache manually to host your specific WSGI application.

See section "Connecting into Apache installation" in:

* https://pypi.python.org/pypi/mod_wsgi

for more details about the ``module-config`` command.

**Comment by opteamix-pkumar** [comment]
hey by entering the command mod_wsgi-express module-config i am getting this error?

C:\Users\pkumar>mod_wsgi-express module-config
Traceback (most recent call last):
  File "e:\pythonpro\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\pythonpro\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\pythonpro\Scripts\mod_wsgi-express.exe\__main__.py", line 5, in <module>
  File "e:\pythonpro\lib\site-packages\mod_wsgi\server\__init__.py", line 24, in <module>
    from . import apxs_config
  File "e:\pythonpro\lib\site-packages\mod_wsgi\server\apxs_config.py", line 27
    LIBEXECDIR = 'C:\Users\pkumar\Desktop\servers\Apache24/lib'
                ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by GrahamDumpleton** [comment]
@opteamix-pkumar Create a new issue. Please don't ask questions on old issues, especially closed issues. Thanks.

**Comment by Muniraj577** [comment]
Hi, all on running command mod_wsgi-express module-config, I am getting the following error.

`Traceback (most recent call last):
  File "C:\Users\pirat\AppData\Local\Programs\Python\Python37\Scripts\mod_wsgi-express-script.py", line 11, in <module>
    load_entry_point('mod-wsgi==4.7.1', 'console_scripts', 'mod_wsgi-express')()
  File "c:\users\pirat\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\pirat\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "c:\users\pirat\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "c:\users\pirat\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\pirat\appdata\local\programs\python\python37\lib\site-packages\mod_wsgi\server\__init__.py", line 25, in <module>
    from . import apxs_config
  File "c:\users\pirat\appdata\local\programs\python\python37\lib\site-packages\mod_wsgi\server\apxs_config.py", line 27
    LIBEXECDIR = 'C:\xampp\apache\/lib'
                ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-4: truncated \xXX escape`
Thanks..

**Comment by GrahamDumpleton** [comment]
Did you read the above comment where already said to someone else not to use a comment for a new issue???

That said, somewhere along the way when you installed something you used Windows backslashes for path separator. If you are overriding ``APACHE_ROOT_DIR`` environment variable when installing mod_wsgi, you must use Posix style forward slashes as the path separator. So try again, with variable set correctly. Ensure you use ``--no-cache-dir`` option to ``pip`` so it rebuilds everything and doesn't use the cached version.

If that doesn't help, create a new issue, and with details above ensure you give all the commands you ran to do the installation.
