### ISSUE TITLE
error while verifying installation of mod_wsgi

### ISSUE THREAD

**Issue by yashaswiniuma** [GrahamDumpleton/mod_wsgi#236]
C:\>mod_wsgi-express start-server
Traceback (most recent call last):
  File "C:\Python27\Scripts\mod_wsgi-express-script.py", line 11, in <module>
    load_entry_point('mod-wsgi==4.5.20', 'console_scripts', 'mod_wsgi-express')( )
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2755, in
load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2409, in
load
    return self.resolve()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2415, in
resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python27\lib\site-packages\mod_wsgi\server\__init__.py", line 24, in
<module>
    from . import apxs_config
ValueError: invalid \x escape

C:\>mod_wsgi-express start-server
Traceback (most recent call last):
  File "C:\Python27\Scripts\mod_wsgi-express-script.py", line 11, in <module>
    load_entry_point('mod-wsgi==4.5.20', 'console_scripts', 'mod_wsgi-express')()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2409, in load
    return self.resolve()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python27\lib\site-packages\mod_wsgi\server\__init__.py", line 24, in
<module>
    from . import apxs_config
ValueError: invalid \x escape

**Comment by GrahamDumpleton** [comment]
You can't use ``mod_wsgi-express start-server`` on Windows. You are meant to run:

```
mod_wsgi-express module-config
```

and take the output of that command and add that to an existing Apache installation to have it load the mod_wsgi module.

If that output had ``None`` at the end of the ``LoadModule`` line value, change ``None`` to ``.pyd``.

Restart Apache to see if it will restart or fails.

It may fail as Python 2.7 appears that it may not work with recent Apache builds. This may be because Python 2.7 requires VC9 compiled versions of Apache and only later versions are available.

I would really recommend using Python 3.6 instead.

**Comment by yashaswiniuma** [comment]
thank you so much for the reply sir,
i am able to deploy my python application with 127.0.0.1:5000.
but i want to access my application in other systems by using my IP(my system is server).
mine is mtech project it is small application.
server i am using is apche 2.4(part of Xampp).
already i have developed most part of code in python 2.7.

Thank you in advance.

**Comment by GrahamDumpleton** [comment]
Have you read through any of the documentation at:

* http://www.modwsgi.org

**Comment by yashaswiniuma** [comment]
is it possible to deploy with IP by using python 2.7,windows ?

**Comment by GrahamDumpleton** [comment]
If you do not use a ``VirtualHost``, or ensure the config is in the first ``VirtualHost``, Apache doesn't care whether you access it by the IP address, or whatever hostname the machine is known as. In the case of using the first ``VirtualHost``, Apache will use that even if name based host lookup doesn't match, as it falls back to the first ``VirtualHost``.

**Comment by GrahamDumpleton** [comment]
You can see a discussion about fallback to first virtual host in:

* http://blog.dscpl.com.au/2012/10/requests-running-in-wrong-django.html
