### ISSUE TITLE
Mod_wsgi fails to find module _cffi_backend

### ISSUE THREAD

**Issue by benhg** [GrahamDumpleton/mod_wsgi#269]
Hello,

I am using mod_wsgi compiled for python3.5 with apache version 2.4.6 on CentOs 7. I am getting an import error stating that the module _cffi_backend (which I assume is a c header file) cannot be found. I have verified that all of my environment variables (PYTHONPATH, LD_LIBRARY_PATH, etc) and apache mod_wsgi options (python-home, etc) are set correctly. This import works fine with the same environment variables when run directly through python from the command line. I have a suspicion that it has to do with library directories not being included upon compilation. Is there a way I can fix this? Here is an excerpt from my httpd error_log:

```
[Tue Feb 27 18:21:18.458209 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102] mod_wsgi (pid=26868): Target WSGI script '/var/www/cluster-interface/server_base.wsgi' cannot be loaded as Python module.
[Tue Feb 27 18:21:18.458283 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102] mod_wsgi (pid=26868): Exception occurred processing WSGI script '/var/www/cluster-interface/server_base.wsgi'.
[Tue Feb 27 18:21:18.458508 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102] Traceback (most recent call last):
[Tue Feb 27 18:21:18.458579 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]   File "/var/www/cluster-interface/server_base.wsgi", line 23, in <module>
[Tue Feb 27 18:21:18.458587 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]     from app import app as application
[Tue Feb 27 18:21:18.458599 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]   File "/var/www/cluster-interface/app.py", line 9, in <module>
[Tue Feb 27 18:21:18.458605 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]     from libsubmit import GridEngine
[Tue Feb 27 18:21:18.458628 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]   File "/local/cluster/lib/python3.6/site-packages/libsubmit-0.3.0-py3.6.egg/libsubmit/__init__.py", line 24, in <module>
[Tue Feb 27 18:21:18.458635 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]     from libsubmit.channels.ssh.ssh import SshChannel
[Tue Feb 27 18:21:18.458645 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]   File "/local/cluster/lib/python3.6/site-packages/libsubmit-0.3.0-py3.6.egg/libsubmit/channels/ssh/ssh.py", line 3, in <module>
[Tue Feb 27 18:21:18.458650 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]     import paramiko
[Tue Feb 27 18:21:18.458660 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]   File "/local/cluster/lib/python3.6/site-packages/paramiko/__init__.py", line 22, in <module>
[Tue Feb 27 18:21:18.458666 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]     from paramiko.transport import SecurityOptions, Transport
[Tue Feb 27 18:21:18.458676 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]   File "/local/cluster/lib/python3.6/site-packages/paramiko/transport.py", line 57, in <module>
[Tue Feb 27 18:21:18.458681 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]     from paramiko.ed25519key import Ed25519Key
[Tue Feb 27 18:21:18.458690 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]   File "/local/cluster/lib/python3.6/site-packages/paramiko/ed25519key.py", line 17, in <module>
[Tue Feb 27 18:21:18.458695 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]     import bcrypt
[Tue Feb 27 18:21:18.458705 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]   File "/local/cluster/lib/python3.6/site-packages/bcrypt/__init__.py", line 25, in <module>
[Tue Feb 27 18:21:18.458710 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102]     from bcrypt import _bcrypt
[Tue Feb 27 18:21:18.458737 2018] [wsgi:error] [pid 26868] [remote 149.xxx.xx.xx6:38102] ImportError: No module named '_cffi_backend'
```

**Comment by GrahamDumpleton** [comment]
Can you find ``_cffi_backend.so`` anywhere on your system? What path?

**Comment by benhg** [comment]
I can find the following matches for _cffi_backend:
```
/local/cluster/lib/python3.6/site-packages/_cffi_backend.cpython-36m-x86_64-linux-gnu.so
/local/cluster/lib/python3.6/site-packages/.libs_cffi_backend
/local/cluster/lib/python3.6/site-packages/.libs_cffi_backend/libffi-d78936b1.so.6.0.4
```

These should all be in the $PATH
I'm guessing we should just rename one of them to `_cffi_backend.so`

**Comment by GrahamDumpleton** [comment]
If your mod_wsgi is really compiled for Python 3.5, you cannot point it at a virtual environment created using Python 3.6. It would be necessary for mod_wsgi to be compiled for Python 3.6. You can't mix versions. The module isn't being found because it is rejected as being for different Python version.

**Comment by benhg** [comment]
Thank you
