### ISSUE TITLE
Unable to install mod_wsgi in windows 10 64 bit.

### ISSUE THREAD

**Issue by sirajalam049** [GrahamDumpleton/mod_wsgi#281]
I have programs installed - ApacheLounge, mysql, php7, python and pip repository.

I simply ran the command `pip install mod_wsgi`

**Output**

```
 Collecting mod_wsgi
  Using cached mod_wsgi-4.6.2.tar.gz
Building wheels for collected packages: mod-wsgi
  Running setup.py bdist_wheel for mod-wsgi ... error
  Complete output from command d:\business_work\python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ajax\\AppData\\Local\\Temp\\pip-build-i_p777e0\\mod-wsgi\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Ajax\AppData\Local\Temp\tmpvgw68gr6pip-wheel- --python-tag cp34:
  d:\business_work\python34\lib\distutils\dist.py:260: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
```
.
.
.
.   .   .Bunch of copy and creating commands.  .  .
.
.
.

```
running build_ext
  building 'mod_wsgi.server.mod_wsgi' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Ajax\AppData\Local\Temp\pip-build-i_p777e0\mod-wsgi\setup.py", line 588, in <module>
      zip_safe = False,
    File "d:\business_work\python34\lib\distutils\core.py", line 149, in setup
      dist.run_commands()
    File "d:\business_work\python34\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "d:\business_work\python34\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "d:\business_work\python34\lib\site-packages\wheel\bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "d:\business_work\python34\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\business_work\python34\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "d:\business_work\python34\lib\distutils\command\build.py", line 126, in run
      self.run_command(cmd_name)
    File "d:\business_work\python34\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\business_work\python34\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "d:\business_work\python34\lib\site-packages\setuptools\command\build_ext.py", line 52, in run
      _build_ext.run(self)
    File "d:\business_work\python34\lib\distutils\command\build_ext.py", line 348, in run
      self.build_extensions()
    File "d:\business_work\python34\lib\distutils\command\build_ext.py", line 457, in build_extensions
      self.build_extension(ext)
    File "d:\business_work\python34\lib\site-packages\setuptools\command\build_ext.py", line 186, in build_extension
      _build_ext.build_extension(self,ext)
    File "d:\business_work\python34\lib\distutils\command\build_ext.py", line 512, in build_extension
      depends=ext.depends)
    File "d:\business_work\python34\lib\distutils\msvc9compiler.py", line 460, in compile
      self.initialize()
    File "d:\business_work\python34\lib\distutils\msvc9compiler.py", line 371, in initialize
      vc_env = query_vcvarsall(VERSION, plat_spec)
    File "d:\business_work\python34\lib\distutils\msvc9compiler.py", line 287, in query_vcvarsall
      raise ValueError(str(list(result.keys())))
  ValueError: ['path']

----------------------------------------
Failed building wheel for mod-wsgi
  Running setup.py clean for mod-wsgi
Failed to build mod-wsgi
Installing collected packages: mod-wsgi
  Running setup.py install for mod-wsgi ... error
    Complete output from command d:\business_work\python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ajax\\AppData\\Local\\Temp\\pip-build-i_p777e0\\mod-wsgi\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Ajax\AppData\Local\Temp\pip-ucwa3ypj-record\install-record.txt --single-version-externally-managed --compile:
    d:\business_work\python34\lib\distutils\dist.py:260: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_py

```

.
.
.
.   .   .Bunch of copy and creating commands.  .  .
.
.
.

```
running build_ext
    building 'mod_wsgi.server.mod_wsgi' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Ajax\AppData\Local\Temp\pip-build-i_p777e0\mod-wsgi\setup.py", line 588, in <module>
        zip_safe = False,
      File "d:\business_work\python34\lib\distutils\core.py", line 149, in setup
        dist.run_commands()
      File "d:\business_work\python34\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "d:\business_work\python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "d:\business_work\python34\lib\site-packages\setuptools\command\install.py", line 54, in run
        return _install.run(self)
      File "d:\business_work\python34\lib\distutils\command\install.py", line 554, in run
        self.run_command('build')
      File "d:\business_work\python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\business_work\python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "d:\business_work\python34\lib\distutils\command\build.py", line 126, in run
        self.run_command(cmd_name)
      File "d:\business_work\python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\business_work\python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "d:\business_work\python34\lib\site-packages\setuptools\command\build_ext.py", line 52, in run
        _build_ext.run(self)
      File "d:\business_work\python34\lib\distutils\command\build_ext.py", line 348, in run
        self.build_extensions()
      File "d:\business_work\python34\lib\distutils\command\build_ext.py", line 457, in build_extensions
        self.build_extension(ext)
      File "d:\business_work\python34\lib\site-packages\setuptools\command\build_ext.py", line 186, in build_extension
        _build_ext.build_extension(self,ext)
      File "d:\business_work\python34\lib\distutils\command\build_ext.py", line 512, in build_extension
        depends=ext.depends)
      File "d:\business_work\python34\lib\distutils\msvc9compiler.py", line 460, in compile
        self.initialize()
      File "d:\business_work\python34\lib\distutils\msvc9compiler.py", line 371, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "d:\business_work\python34\lib\distutils\msvc9compiler.py", line 287, in query_vcvarsall
        raise ValueError(str(list(result.keys())))
    ValueError: ['path']

    ----------------------------------------
Command "d:\business_work\python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ajax\\AppData\\Local\\Temp\\pip-build-i_p777e0\\mod-wsgi\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Ajax\AppData\Local\Temp\pip-ucwa3ypj-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Ajax\AppData\Local\Temp\pip-build-i_p777e0\mod-wsgi\
```

**My Software Versions:**
WIndows 10 Home Basic 64bit
ApacheLounge 2.4 win64
php 7.2.3
mysql 14.14 Distrib 5.7.21 for win64
python 3.4.0  [MSC v.1600 64 bit (AMD64)]

**Comment by GrahamDumpleton** [comment]
What version of Microsoft C compiler are you using?

The page at:

* https://wiki.python.org/moin/WindowsCompilers

says that for Python 3.4 you are supposed to use Visual C++ 10.0.

The errors in your output mention version VC9 instead of VC10. I don't know if that is the immediate cause of the problem, but you do have to use the correct compiler version for your Python distribution.

Another issue you will encounter is whether you can get a version of ApacheLounge built with VC10. These days it is better to use Python 3.6 and VC14 compiler, as VC14 is what recent ApacheLounge binaries are built with. The compiler version must match for everything to be sure it works.

A final issue, but you haven't even got far enough to use this issue yet, is that for now you want to use:

```
pip install mod_wsgi==4.5.24
```

The 4.6.2 version has an issue with compilation on Windows (not the issue you are seeing though). A fix has been done but was only done today as just found out about issue, so not released yet as 4.6.3.

**Comment by sirajalam049** [comment]
So I uninstalled my python 3.4.x and installed Python 3.6.x and also installed VC14.

But I encountered an error that must be the one you mentioned. So I installed 4.5.24 and everything happened like magic.

Thanks a lot for your time. Now I can start my project Happily.

**Comment by ondrej-ivanko** [comment]
Hello Mr. Dumpleton, just an sidenote from me regarding this issue:

I had almost identical problem, but my C++ compilers were VC 14++ and higher. i installed as many as I could. Everything i had was installed to default folders and were x64 versions on Win 10. I had the latests pip, setuptools, wheel and Python 3.7.3.

The crucial issue turned out to be version of mod_wsgi which I tried to install the latest 6.6 and when I tried 4.5.24 it magically worked after 2 days of trying to solve this issue. There might be some critical error in latest versions.

**Comment by GrahamDumpleton** [comment]
Yes, 4.6.6 has known issue. See https://github.com/GrahamDumpleton/mod_wsgi/issues/436

I have been on a trip so haven't had chance to fix it yet. So use 4.6.5.

**Comment by GrahamDumpleton** [comment]
And I should highlight that the issue with 4.6.6 is totally unrelated to the one this issue was about.

**Comment by ondrej-ivanko** [comment]
Yes, thank you for pointing me to that #436 issue. I wish I´d find it earlier. It totally works.

**Comment by ananthreddy2580** [comment]
> Hello Mr. Dumpleton, just an sidenote from me regarding this issue:
> 
> I had almost identical problem, but my C++ compilers were VC 14++ and higher. i installed as many as I could. Everything i had was installed to default folders and were x64 versions on Win 10. I had the latests pip, setuptools, wheel and Python 3.7.3.
> 
> The crucial issue turned out to be version of mod_wsgi which I tried to install the latest 6.6 and when I tried 4.5.24 it magically worked after 2 days of trying to solve this issue. There might be some critical error in latest versions.

what are the configurations  and versions you used
