### ISSUE TITLE
AttributeError: module 'os' has no attribute 'getuid'

### ISSUE THREAD

**Issue by am2222** [GrahamDumpleton/mod_wsgi#332]
Hi, I am on windows. I wanted to try using django `runmodwsgi` but  I faced this error, what options do I have to fix it?
```
python manage.py runmodwsgi
Successfully ran command.
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python36\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Python36\lib\site-packages\django\core\management\__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python36\lib\site-packages\django\core\management\base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python36\lib\site-packages\django\core\management\base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "C:\Python36\lib\site-packages\mod_wsgi\server\management\commands\runmodwsgi.py", line 134, in handle
    'start-server', args, options)
  File "C:\Python36\lib\site-packages\mod_wsgi\server\__init__.py", line 2660, in _cmd_setup_server
    options['port'], os.getuid())
AttributeError: module 'os' has no attribute 'getuid'

```

**Comment by GrahamDumpleton** [comment]
You can't use ``mod_wsgi-express start-server`` or the Django ``runmodwsgi`` management command integration on Windows. Only UNIX type operating systems are supported by it.
