### ISSUE TITLE
Virtualenv & Django: Target script can not be loaded as python module.

### ISSUE THREAD

**Issue by milossh** [GrahamDumpleton/mod_wsgi#342]
When I first started with django on apache with mod_wsgi, I got this very error, and after fixing my vhost, it went away. From then, up until now, I've successfully ran django, with no issues whatsoever.

Now, all of a sudden, I get the same error again. Here's my vhosts:

```
<VirtualHost *:80>
        <Directory /home/milos/django-doktorino/doktorinosite>
                Options Indexes FollowSymLinks
                AllowOverride All
                Require all granted
​
                Order allow,deny
                Allow from all
        </Directory>
​
        <Location "/">
                AuthType Basic
                AuthName "Password Protected Area"
                AuthUserFile /home/milos/django-doktorino/.htpasswd
                Require valid-user
        </Location>
​
        Alias /static /home/milos/django-doktorino/doktorinosite/static
        <Directory /home/milos/django-doktorino/doktorinosite/static>
                Require all granted
        </Directory>
​
        <Directory /home/milos/django-doktorino/doktorinosite/doktorinosite>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>
​
        WSGIDaemonProcess doktorinosite python-home=/home/milos/django-doktorino/env python-path=/home/milos/django-doktorino/doktorinosite
​
        WSGIProcessGroup doktorinosite
        WSGIApplicationGroup %{GLOBAL}
​
        WSGIScriptAlias / /home/milos/django-doktorino/doktorinosite/doktorinosite/wsgi.py
​
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```
and full traceback from apache2 error.log file:

```
[Sun Jul 15 02:53:20.885212 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929] mod_wsgi (pid=21980): Target WSGI script '/home/milos/django-doktorino/doktorinosite/doktorinosite/wsgi.py' cannot be loaded as Python module.
[Sun Jul 15 02:53:20.885268 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929] mod_wsgi (pid=21980): Exception occurred processing WSGI script '/home/milos/django-doktorino/doktorinosite/doktorinosite/wsgi.py'.
[Sun Jul 15 02:53:20.885448 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929] Traceback (most recent call last):
[Sun Jul 15 02:53:20.885490 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]   File "/home/milos/django-doktorino/doktorinosite/doktorinosite/wsgi.py", line 17, in <module>
[Sun Jul 15 02:53:20.885494 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]     application = get_wsgi_application()
[Sun Jul 15 02:53:20.885504 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]   File "/home/milos/django-doktorino/env/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Sun Jul 15 02:53:20.885508 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]     django.setup(set_prefix=False)
[Sun Jul 15 02:53:20.885516 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]   File "/home/milos/django-doktorino/env/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
[Sun Jul 15 02:53:20.885520 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]     apps.populate(settings.INSTALLED_APPS)
[Sun Jul 15 02:53:20.885533 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]   File "/home/milos/django-doktorino/env/lib/python3.5/site-packages/django/apps/registry.py", line 81, in populate
[Sun Jul 15 02:53:20.885537 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]     raise RuntimeError("populate() isn't reentrant")
[Sun Jul 15 02:53:20.885556 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929] RuntimeError: populate() isn't reentrant
[Sun Jul 15 02:53:20.962896 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929] mod_wsgi (pid=21980): Target WSGI script '/home/milos/django-doktorino/doktorinosite/doktorinosite/wsgi.py' cannot be loaded as Python module.
[Sun Jul 15 02:53:20.962969 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929] mod_wsgi (pid=21980): Exception occurred processing WSGI script '/home/milos/django-doktorino/doktorinosite/doktorinosite/wsgi.py'.
[Sun Jul 15 02:53:20.963221 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929] Traceback (most recent call last):
[Sun Jul 15 02:53:20.963321 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]   File "/home/milos/django-doktorino/doktorinosite/doktorinosite/wsgi.py", line 17, in <module>
[Sun Jul 15 02:53:20.963329 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]     application = get_wsgi_application()
[Sun Jul 15 02:53:20.963345 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]   File "/home/milos/django-doktorino/env/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Sun Jul 15 02:53:20.963352 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]     django.setup(set_prefix=False)
[Sun Jul 15 02:53:20.963368 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]   File "/home/milos/django-doktorino/env/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
[Sun Jul 15 02:53:20.963374 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]     apps.populate(settings.INSTALLED_APPS)
[Sun Jul 15 02:53:20.963390 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]   File "/home/milos/django-doktorino/env/lib/python3.5/site-packages/django/apps/registry.py", line 81, in populate
[Sun Jul 15 02:53:20.963396 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929]     raise RuntimeError("populate() isn't reentrant")
[Sun Jul 15 02:53:20.963428 2018] [wsgi:error] [pid 21980] [remote 178.149.67.77:21929] RuntimeError: populate() isn't reentrant
```

Please at least help with debugging this.

I'm running Apache2 with mod_wsgi on Ubuntu 16.04.

**Comment by GrahamDumpleton** [comment]
The ``populate() isn't reentrant`` error is a secondary error. You must go back through the logs and find the error that precedes it which occurred immediately the process was restarted and the WSGI script first loaded. That will tell you what the real problem is. Often it is a mistake in your settings file.

**Comment by milossh** [comment]
This is the full log since I restarted apache2.

**Comment by GrahamDumpleton** [comment]
Then your code is somehow trigger initialisation of Django twice all by itself then.

Are you calling ``django.setup()`` explicitly from your code somehow?

**Comment by milossh** [comment]
Nope, nowhere do I do that in my code.

**Comment by GrahamDumpleton** [comment]
What is in your WSGI script file?

**Comment by milossh** [comment]
```
cat doktorinosite/wsgi.py
#!/usr/bin/env python3
"""
WSGI config for doktorinosite project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "doktorinosite.settings")

application = get_wsgi_application()
```

**Comment by GrahamDumpleton** [comment]
Set ``LogLevel info`` in ``VirtualHost``. Restart Apache. Make a single request. Then show the log from when Apache restarted. Include the bits where Apache restarted so can be certain that restart occurred.

**Comment by milossh** [comment]
At some point, I got an import error. Now that I fixed that, everything works OK again.
