### ISSUE TITLE
mod_wsgi (pid=10266): Failed to exec Python script file '.../wsgi.py'

### ISSUE THREAD

**Issue by rbelew** [GrahamDumpleton/mod_wsgi#353]
i'm installing on an AWS ubuntu 16.04 instance.  after following your hints here https://stackoverflow.com/a/44915354,  i've replaced the system mod_wsgi with the newer mod_wsgi.  `mod_wsgi-express module-config` produces `LoadModule wsgi_module ".../.local/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-x86_64-linux-gnu.so"`

i've added this to the config file included by apache. after an apache restart, I now get this line in its error log:

`AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.6.4 Python/3.5 configured -- resuming normal operations`

all versions see correct?

but then on first attempt to hit the server i get:

```
	mod_wsgi (pid=10266): Failed to exec Python script file '.../wsgi.py'

	Traceback (most recent call last):
	File ".../wsgi.py", line 17, in <module>
	from django.core.wsgi import get_wsgi_application
	ImportError: No module named 'django'
```
i put this `for f in sys.path: print(f)` just before the troublesome import in `wsgi.py` and it shows:

```
	.../.local/lib/python3.5/site-packages
	/usr/lib/python35.zip
	/usr/lib/python3.5
	/usr/lib/python3.5/plat-x86_64-linux-gnu
	/usr/lib/python3.5/lib-dynload
	/usr/local/lib/python3.5/dist-packages
	/usr/lib/python3/dist-packages
```
but when i check to see where django is install:

```
	% python3
	Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
	[GCC 5.4.0 20160609] on linux
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import django
	>>> django.__file__
	'.../.local/lib/python3.5/site-packages/django/__init__.py'
```
i'll also note that i've permitted `.local/lib`:

```
    cd ~/.local/
    chmod -R go+rx lib
```
it seems mod_wsgi should be able to find django in my `site-packages`.  

Graham's response:

> FWIW though, your code runs as the Apache user, not you, so it isn't going to look in your personal site-packages directory. 

i realize the process runs with apache user, and that this requires the files be permitted.  but if the path is part of sys.path and accessible, why does it not go there?

> Create a separate virtual environment and use it. 

i can't think of a reason why i should want to bring a venv into this AWS instance?

**Comment by GrahamDumpleton** [comment]
What are the permissions on your home directory? It often isn't ``o+rx``. So when I meant create a separate virtual environment, I mean to have it, plus your project code not under a home directory that Apache user can't see in to.

Can you also provide your Apache config for mod_wsgi. Please don't trim parts of paths. If you want to mask your username, replace just the username with ``xxx``.

**Comment by rbelew** [comment]
good catch, i did find one directory `/home/USER/.local` that was NOT permitted `o+rx`.

and so now it gets a bit farther, 
```
mod_wsgi (pid=20093): Failed to exec Python script file '/home/USER/django/showCrime/showCrime/wsgi.py'.
mod_wsgi (pid=20093): Exception occurred processing WSGI script '/home/USER/django/showCrime/showCrime/wsgi.py'.
Traceback (most recent call last):
   File "/home/USER/django/showCrime/showCrime/wsgi.py", line 21, in <module>
     application = get_wsgi_application()
   File "/home/USER/.local/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
   django.setup(set_prefix=False)
   File "/home/USER/.local/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
   configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
   File "/home/USER/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
   self._setup(name)
   File "/home/USER/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
   self._wrapped = Settings(settings_module)
   File "/home/USER/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
   mod = importlib.import_module(self.SETTINGS_MODULE)
   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
   return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
   File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
   File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'showCrime'
```
ie, `.../site-packages/django/__init__.py` isn't aware of my application's module?!

> Can you also provide your Apache config for mod_wsgi. 

here you go:

```
LoadModule wsgi_module "/home/USER/.local/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-x86_64-linux-gnu.so"

WSGIPythonHome "/usr"

WSGIScriptAlias / /home/USER/django/showCrime/showCrime/wsgi.py
WSGIPythonPath /home/USER/.local/lib/python3.5/site-packages:/home/USER/django/showCrime

<Directory /home/USER/django/showCrime/showCrime>
<Files wsgi.py>
Require all granted
</Files>
</Directory>
```

**Comment by rbelew** [comment]
good catch, i did find one directory `/home/USER/.local` that was NOT permitted `o+rx`.

and so now it gets a bit farther, 
```
mod_wsgi (pid=20093): Failed to exec Python script file '/home/USER/django/showCrime/showCrime/wsgi.py'.
mod_wsgi (pid=20093): Exception occurred processing WSGI script '/home/USER/django/showCrime/showCrime/wsgi.py'.
Traceback (most recent call last):
File "/home/USER/django/showCrime/showCrime/wsgi.py", line 21, in <module>
application = get_wsgi_application()
File "/home/USER/.local/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
django.setup(set_prefix=False)
File "/home/USER/.local/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
File "/home/USER/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
self._setup(name)
File "/home/USER/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
self._wrapped = Settings(settings_module)
File "/home/USER/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
mod = importlib.import_module(self.SETTINGS_MODULE)
File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 986, in _gcd_import
File "<frozen importlib._bootstrap>", line 969, in _find_and_load
File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 986, in _gcd_import
File "<frozen importlib._bootstrap>", line 969, in _find_and_load
File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'showCrime'
```
ie, `.../site-packages/django/__init__.py` isn't aware of my application's module?!

> Can you also provide your Apache config for mod_wsgi. 

here you go:

```
LoadModule wsgi_module "/home/USER/.local/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-x86_64-linux-gnu.so"

WSGIPythonHome "/usr"

WSGIScriptAlias / /home/USER/django/showCrime/showCrime/wsgi.py
WSGIPythonPath /home/USER/.local/lib/python3.5/site-packages:/home/USER/django/showCrime

<Directory /home/USER/django/showCrime/showCrime>
<Files wsgi.py>
Require all granted
</Files>
</Directory>
```

**Comment by rbelew** [comment]
FIXED!  for any of you bumping into this issue: this last issue was simply that i had not added my django app's directory to `WSGIPythonPath`:  `WSGIPythonPath /home/USER/venv/django:/home/USER/django/showCrime`
