### ISSUE TITLE
Target WSGI script cannot be loaded as a python module and ImportError: No module named 'django'

### ISSUE THREAD

**Issue by satishAarbor** [GrahamDumpleton/mod_wsgi#378]
0
down vote
favorite
I'm try to deploy virtual host my django project into apache2 via mod_wsgi WSGIDaemon method, i'm using ubuntu 16.04 and i'm getting following error.

From apache2 error log:

[Tue Dec 11 11:55:31.748517 2018] [wsgi:error] [pid 14231:tid 139821891782400] [remote ::1:44748] mod_wsgi (pid=14231): Target WSGI script '/var/www/html/rasa_django/rasa_django/wsgi.py' cannot be loaded as Python module. [Tue Dec 11 11:55:31.748570 2018] [wsgi:error] [pid 14231:tid 139821891782400] [remote ::1:44748] mod_wsgi (pid=14231): Exception occurred processing WSGI script '/var/www/html/rasa_django/rasa_django/wsgi.py'. [Tue Dec 11 11:55:31.748639 2018] [wsgi:error] [pid 14231:tid 139821891782400] [remote ::1:44748] Traceback (most recent call last): [Tue Dec 11 11:55:31.748657 2018] [wsgi:error] [pid 14231:tid 139821891782400] [remote ::1:44748] File "/var/www/html/rasa_django/rasa_django/wsgi.py", line 12, in [Tue Dec 11 11:55:31.748662 2018] [wsgi:error] [pid 14231:tid 139821891782400] [remote ::1:44748] from django.core.wsgi import get_wsgi_application [Tue Dec 11 11:55:31.748677 2018] [wsgi:error] [pid 14231:tid 139821891782400] [remote ::1:44748] ImportError: No module named 'django' [Tue Dec 11 11:55:31.787336 2018] [wsgi:error] [pid 14231:tid 139821849777920] [remote ::1:38604] mod_wsgi (pid=14231): Target WSGI script '/var/www/html/rasa_django/rasa_django/wsgi.py' cannot be loaded as Python module. [Tue Dec 11 11:55:31.787379 2018] [wsgi:error] [pid 14231:tid 139821849777920] [remote ::1:38604] mod_wsgi (pid=14231): Exception occurred processing WSGI script '/var/www/html/rasa_django/rasa_django/wsgi.py'. [Tue Dec 11 11:55:31.787447 2018] [wsgi:error] [pid 14231:tid 139821849777920] [remote ::1:38604] Traceback (most recent call last): [Tue Dec 11 11:55:31.787465 2018] [wsgi:error] [pid 14231:tid 139821849777920] [remote ::1:38604] File "/var/www/html/rasa_django/rasa_django/wsgi.py", line 12, in [Tue Dec 11 11:55:31.787470 2018] [wsgi:error] [pid 14231:tid 139821849777920] [remote ::1:38604] from django.core.wsgi import get_wsgi_application [Tue Dec 11 11:55:31.787484 2018] [wsgi:error] [pid 14231:tid 139821849777920] [remote ::1:38604] ImportError: No module named 'django'

In my host file 000-default.conf:

ServerName www.rasa_django.com DocumentRoot /var/www/html/rasa_django ErrorLog /var/www/logs/error.log CustomLog /var/www/logs/custom.log combined

Alias /static /var/www/html/rasa_django/static

<Directory /var/www/html/rasa_django/static>
    Require all granted
</Directory>

<Directory /var/www/html/rasa_django/rasa_django>
    <Files wsgi.py>
        Require all granted
    </Files>
</Directory>

WSGIDaemonProcess rasa_django.com python-path=/var/www/html/rasa_django python-home=/home/aarbor_01/env_site1/lib/python3.6/site-packages
WSGIProcessGroup rasa_django.com
WSGIScriptAlias / /var/www/html/rasa_django/rasa_django/wsgi.py
Here my wsgi.py file:

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'rasa_django.settings')

application = get_wsgi_application()``

**Comment by GrahamDumpleton** [comment]
For a start, ``python-home`` is not meant to refer to ``site-packages``. It is meant to refer to the root of the Python virtual environment. See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

**Comment by satishAarbor** [comment]
I tried it but still i'm facing this issues

**Comment by GrahamDumpleton** [comment]
What are the permissions on your home directory?

```
ls -lasd /home/aarbor_01
```

Home directories on some operating systems cannot be read by other users, and so would not be accessible to the user that Apache runs as.

You should also check what permissions are used on the Python virtual environments directories/files as well.

In general you are better off having both the project and Python virtual environment outside of your home directory.

That all said, when you have activated the Python virtual environment and run the Python interpreter, what do you get for:

```
import sys
print(sys.prefix)

import django
print(django.__file__)
```

Show me what you are now using for the Apache configuration.

**Comment by satishAarbor** [comment]
aarbor_01@aarbor01-virtual-machine:~$  ls -lasd /home/aarbor_01
4 drwxr-xr-x 57 aarbor_01 aarbor_01 4096 Dec 12 09:37 /home/aarbor_01

**Comment by satishAarbor** [comment]
(env_site1) aarbor_01@aarbor01-virtual-machine:~$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.prefix)
/home/aarbor_01/env_site1
>>> import django
>>> print(django.__file__)
/home/aarbor_01/env_site1/lib/python3.6/site-packages/django/__init__.py

**Comment by satishAarbor** [comment]
following code is my apache 000-default.conf now i'm using


<VirtualHost *:80>
	ServerName rasa_django.com
	DocumentRoot /var/www/html
	ErrorLog /var/www/logs/error.log
	CustomLog /var/www/logs/custom.log combined
	WSGIScriptAlias / /var/www/html/rasa_django/rasa_django/wsgi.py
	Alias /static /var/www/html/rasa_django/static

	<Directory /var/www/html/rasa_django/static>
		Require all granted
	</Directory>

	<Directory /var/www/html/rasa_django/rasa_django>
		<Files wsgi.py>
			Require all granted
		</Files>
	</Directory>

	WSGIDaemonProcess rasa_django.com python-path=/var/www/html/rasa_django python-home=/home/aarbor_01/env_site1
    WSGIProcessGroup rasa_django.com
    </VirtualHost>

**Comment by GrahamDumpleton** [comment]
How did you install mod_wsgi?

It must be compiled for the specific Python installation/version you are using. You cannot use system package for mod_wsgi (which is compiled for system package for Python), with a virtual environment created using Anaconda Python.

**Comment by satishAarbor** [comment]
this is the command i used to install mod_wsgi  

> sudo apt-get install apache2 libapache2-mod-wsgi-py3

**Comment by GrahamDumpleton** [comment]
You can't use the system package for mod_wsgi with Anaconda Python.

You either need to use the system Python for your virtual environment, or you need to uninstall system package for mod_wsgi and install mod_wsgi from source code, using Anaconda Python when you build it.

Easiest method for building from source code is ``pip install`` method. See:

* https://pypi.org/project/mod_wsgi/

**Comment by satishAarbor** [comment]
I'm going to uninstall system package for mod_wsgi but accidentally i uninstalled apache2 now i installed it back and updated the conf file but when i try to restart the apache2 it says 
`aarbor_01@aarbor01-virtual-machine:~$ sudo apache2ctl configtest
AH00526: Syntax error on line 49 of /etc/apache2/sites-enabled/000-default.conf:
Invalid command 'WSGIDaemonProcess', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.
The Apache error log may have more information`

last time i corrected this error from installing and enabling by

> sudo apt-get install apache2 libapache2-mod-wsgi-py3
> sudo enmode wsgi

those command but now it says no module named wsgi

**Comment by GrahamDumpleton** [comment]
If you want to use Anaconda Python, you want to do:

```
sudo a2dismod wsgi
sudo apt-get uninstall libapache2-mod-wsgi-py3
```

and use ``pip install`` method to install mod_wsgi in the Python virtual environment.

Then create a ``wsgi.load`` file in the ``mods-available`` directory of Apache which contains the output from running:

```
mod_wsgi-express module-config
```

Then run:

```
sudo a2enmod wsgi
```

**Comment by satishAarbor** [comment]
what should i do now?

**Comment by satishAarbor** [comment]
following code is my 000-default.conf but still i'm facing the issues


```
<VirtualHost *:80>
	
	ServerAdmin webmaster@localhost
	ServerName www.rasa_django.com
	DocumentRoot /var/www/html/rasa_django
	ErrorLog /var/www/logs/error.log
	CustomLog /var/www/logs/custom.log combined
	
	Alias /static /var/www/html/rasa_django/static

	<Directory /var/www/html/rasa_django/static>
		Require all granted
	</Directory>

	<Directory /var/www/html/rasa_django/rasa_django>
		<Files wsgi.py>
			Require all granted
		</Files>
	</Directory>

	WSGIDaemonProcess rasa_django.com python-home=/home/aarbor_01/env1
    WSGIScriptAlias / /var/www/html/rasa_django/rasa_django/wsgi.py
</VirtualHost>
```

**Comment by GrahamDumpleton** [comment]
Add back the:

```
python-path=/var/www/html/rasa_django
```

option to ``WSGIDaemonProcess`` which I asked about. You should have both it and the ``python-home`` option. The ``python-home``says where the virtual environment is. The ``python-path`` says where your project code is.

**Comment by satishAarbor** [comment]
```
WSGIDaemonProcess rasa_django.com python-home=/home/aarbor_01/env1 python-path=/var/www/html/rasa_django
    WSGIScriptAlias / /var/www/html/rasa_django/rasa_django/wsgi.py
```

**Comment by GrahamDumpleton** [comment]
You are missing ``WSGIProcessGroup``, which I also asked about. For good measure you also should have ``WSGIApplicationGroup``. So use:

```
WSGIDaemonProcess rasa_django.com python-home=/home/aarbor_01/env1 python-path=/var/www/html/rasa_django
WSGIProcessGroup rasa_django.com
WSGIApplicationGroup %{GLOBAL}
WSGIScriptAlias / /var/www/html/rasa_django/rasa_django/wsgi.py
```

You can find further details in the Django docs about daemon mode and what is required:

* https://docs.djangoproject.com/en/2.1/howto/deployment/wsgi/modwsgi/#using-mod-wsgi-daemon-mode

**Comment by satishAarbor** [comment]
`[Wed Dec 12 16:14:30.073887 2018] [wsgi:error] [pid 9437:tid 140119264679680] (2)No such file or directory: [client 127.0.0.1:44446] mod_wsgi (pid=9437): Unable to connect to WSGI daemon process 'rasa_django.com' on '/etc/apache2/logs/wsgi.9432.0.1.sock' as user with uid=33.`

**Comment by GrahamDumpleton** [comment]
See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/configuration-issues.html#location-of-unix-sockets

One other thing, you likely should not be placing your project code under ``/var/www/html``. If the global ``DocumentRoot`` directive is set to ``/var/www/html`` as suspect it might, anyone could potentially download your source. You should never place your source code for your Python application in the directory used by ``DocumentRoot`` as a default, or in any virtual host either.

**Comment by satishAarbor** [comment]
- https://modwsgi.readthedocs.io/en/develop/user-guides/configuration-issues.html#location-of-unix-sockets

by above link it refer to install python dev packages after i installed it the issue was not solved

**Comment by GrahamDumpleton** [comment]
That link doesn't say anything about installing dev packages, so I don't know what you are reading.

That link talks about the need to set ``WSGISocketPrefix`` when the default of ``/etc/httpd/logs`` is not accessible to non root user.

**Comment by satishAarbor** [comment]
how to solve it?

> No such file or directory: [client 127.0.0.1:54146] mod_wsgi (pid=1954): Unable to connect to WSGI daemon process 'rasa_django' on '/etc/apache2/logs/wsgi.1944.0.1.sock' as user with uid=33., referer: http://rasa_django.com/

**Comment by GrahamDumpleton** [comment]
I have already pointed out the information twice. Have you tried adding the ``WSGISocketPrefix`` directive mentioned in the docs at:

* https://modwsgi.readthedocs.io/en/develop/user-guides/configuration-issues.html#location-of-unix-sockets

Show me that you have done this by showing your updated configuration and the latest error.

Ensure that the ``WSGISocketPrefix`` directive is placed outside of the ``VirtualHost``. Read the docs about what path to try adding as the value for that directive.

**Comment by wmorenog** [comment]
Hi SatisAarbor, can you please help, how you solve this issue. I have a CentOS 7  operating system and y have the same error: 
[wsgi:error] [pid 32178] (13)Permission denied: [client x.x.x.x:50906] mod_wsgi (pid=32178): Unable to connect to WSGI daemon process 'django' on '/etc/httpd/run/wsgi.32173.0.1.sock' as user with uid=995., referer: https://x.x.x.x:8000/.
I create a directory wsgi in /run/httpd/ and configure the directive WSGISocketPrefix run/wsgi, but don't work. 
Thanks

**Comment by GrahamDumpleton** [comment]
@wmorenog Please don't ask new questions on old issues. Create a new issue and fully explain you problem with any error messages, what your were doing etc etc. Include what you have tried as far as setting the `WSGISocketPrefix` directive which has already been offered as solution for what you describe. Anyway, move it to a new issue please. Thanks.

**Comment by VishvajeetRamanuj** [comment]
> 
> 
> What are the permissions on your home directory?
> 
> ```
> ls -lasd /home/aarbor_01
> ```
> 
> Home directories on some operating systems cannot be read by other users, and so would not be accessible to the user that Apache runs as.
> 
> You should also check what permissions are used on the Python virtual environments directories/files as well.
> 
> In general you are better off having both the project and Python virtual environment outside of your home directory.
> 
> That all said, when you have activated the Python virtual environment and run the Python interpreter, what do you get for:
> 
> ```
> import sys
> print(sys.prefix)
> 
> import django
> print(django.__file__)
> ```
> 
> Show me what you are now using for the Apache configuration.

I have similar error.  I am getting below output for this command.
Note that i have installed django in my virtualenv and I activated it and then I run below command
```
>>> import django
>>> django.file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'django' has no attribute 'file'
```

**Comment by GrahamDumpleton** [comment]
@vis7 If you still have a problem, then create a separate new issue with all the details of the problem, including configuration, errors, logs etc. Do not ask about your separate problem on an existing issue.
