### ISSUE TITLE
ImportError for configuration settings file in separate virtualenv than the one used for DaemonProcess 

### ISSUE THREAD

**Issue by orkuva** [GrahamDumpleton/mod_wsgi#423]
I have specified a virtual environment in my apache `virtualhost.conf`file. It uses `WSGIDaemonProcess` to link itself to the root of the virtual environment. The root of the virtualenv is in the same directory as my production site. The staging site has its own directory outside of the production site directory level. 

**The problem: Once I start apache and go to either staging or production site, it works fine and lets me login. Once I login to one of them, and then go to the other one, it only takes me to the login page but does not login (apache shows a error in `error_log`).** 

I have pasted the virtual host config and error log below.

```
NameVirtualHost *:80
NameVirtualHost *:443

<VirtualHost *:80>
	ServerAdmin <my-email>
	ServerName <my-prod-website>
	Redirect permanent / <my-https-website>/
</VirtualHost>

WSGISocketPrefix run/wsgi

WSGIDaemonProcess dwm_py python-home=/var/www/dwm/dwmenv

<VirtualHost *:443>
	ServerAdmin <my-email>
	ServerName <my-website>
	SSLEngine On

##### Archive Site #######    
    Alias /archive/static/ /var/www/staging_dwm2/public/static/
	<Directory /var/www/staging_dwm2/public/static>
		Require all granted
	</Directory>
	WSGIScriptAlias /archive /var/www/staging_dwm2/app/wsgi.py
	<Directory /var/www/staging_dwm2/app>
		Require all granted
	</Directory>
       
 #### Main Site ##### 
	Alias /static/ /var/www/dwm/public/static/
	<Directory /var/www/dwm/public/static>
		Require all granted
	</Directory>
	WSGIScriptAlias / /var/www/dwm/app/wsgi.py
	WSGIPassAuthorization On
	<Directory /var/www/dwm/app>
		Require all granted
	</Directory>
</VirtualHost> 
```
```
Wed May 15 09:57:26.350084 2019] [ssl:debug] [pid 4826] ssl_engine_kernel.c(1891): [client 199.111.225.52:13015] AH02043: SSL virtual host for servername <mywebsite> found
[Wed May 15 09:57:26.350479 2019] [:info] [pid 4825] [client 199.111.225.52:13030] mod_wsgi (pid=4825, process='', application='<mywebsite>|'): Loading WSGI script '/var/www/dwm/app/wsgi.py'.
[Wed May 15 09:57:26.357010 2019] [ssl:debug] [pid 4826] ssl_engine_kernel.c(1824): [client 199.111.225.52:13015] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
[Wed May 15 09:57:26.460945 2019] [:error] [pid 4825] [client 199.111.225.52:13030] mod_wsgi (pid=4825): Exception occurred processing WSGI script '/var/www/dwm/app/wsgi.py'.
[Wed May 15 09:57:26.460996 2019] [:error] [pid 4825] [client 199.111.225.52:13030] Traceback (most recent call last):
[Wed May 15 09:57:26.461017 2019] [:error] [pid 4825] [client 199.111.225.52:13030]   File "/var/www/dwm/dwmenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
[Wed May 15 09:57:26.461149 2019] [:error] [pid 4825] [client 199.111.225.52:13030]     self.load_middleware()
[Wed May 15 09:57:26.461166 2019] [:error] [pid 4825] [client 199.111.225.52:13030]   File "/var/www/dwm/dwmenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
[Wed May 15 09:57:26.461272 2019] [:error] [pid 4825] [client 199.111.225.52:13030]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Wed May 15 09:57:26.461287 2019] [:error] [pid 4825] [client 199.111.225.52:13030]   File "/var/www/dwm/dwmenv/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
[Wed May 15 09:57:26.461380 2019] [:error] [pid 4825] [client 199.111.225.52:13030]     self._setup(name)
[Wed May 15 09:57:26.461394 2019] [:error] [pid 4825] [client 199.111.225.52:13030]   File "/var/www/dwm/dwmenv/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
[Wed May 15 09:57:26.461408 2019] [:error] [pid 4825] [client 199.111.225.52:13030]     self._wrapped = Settings(settings_module)
[Wed May 15 09:57:26.461415 2019] [:error] [pid 4825] [client 199.111.225.52:13030]   File "/var/www/dwm/dwmenv/lib/python2.7/site-packages/django/conf/__init__.py", line 134, in __init__
[Wed May 15 09:57:26.461426 2019] [:error] [pid 4825] [client 199.111.225.52:13030]     raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
[Wed May 15 09:57:26.461452 2019] [:error] [pid 4825] [client 199.111.225.52:13030] ImportError: Could not import settings 'conf.staging_dwm2' (Is it on sys.path?): No module named staging_dwm2
```

**Comment by GrahamDumpleton** [comment]
Read:

* http://blog.dscpl.com.au/2012/10/requests-running-in-wrong-django.html

When running multiple sites, you must change the ``wsgi.py`` to not use ``os.environ.setdefault()`` as it causes leakage of ``DJANGO_SETTINGS_MODULE`` between applications.

Further, although you have added ``WSGIDaemonProcess``, you haven't told the sites to run in the daemon process group. That is, you are missing ``WSGIProcessGroup`` directive.

Ideally you would create two daemon process groups and delegate each to a separate one. Right now they are both running both in the Apache processes and not the daemon process group.
