### ISSUE TITLE
Django/pip/Apache - Failed to exec Python script file 'wsgi.py' No module named 'math'

### ISSUE THREAD

**Issue by RobertHosking** [GrahamDumpleton/mod_wsgi#431]
Python 3.7.3
pip 19.1.1
Linux Mint 18.3

I have disabled it `a2dismod wsgi` and uninstalled system packages `apt remove libapache2-mod-wsgi libapache2-mod-wsgi-py3`
I have installed mod_wsgi via pip with `pip install mod_wsgi`
I pasted the output of `mod_wsgi-express module-config` in `/etc/apache2/apache2.conf`
```
LoadModule wsgi_module "/usr/local/lib/python3.7/dist-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so"
WSGIPythonHome "/usr"
```
I have this virtual host (using virtualenv at `/var/www/html/paper/.env/`): 
```
<VirtualHost *:80>
	
    ServerName paper.example.com
    Alias /static/ /var/www/html/paper/static/
    <Directory /var/www/html/paper/static>
        Require all granted
    </Directory>

    WSGIScriptAlias / /var/www/html/paper/src/paperless/wsgi.py
    WSGIDaemonProcess paperless user=r group=paperless threads=5 python-path=/var/www/html/paper/src:/var/www/html/paper/.env/lib/python3.7/site-packages
    WSGIProcessGroup paperless

    <Directory /var/www/html/paper/src/paperless>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

</VirtualHost>
```
and this `wsgi.py`
```
import os
from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "paperless.settings")
application = get_wsgi_application()
```
Visiting `paper.example.com` gives 500 error.
Here are the apache logs:
```
 [wsgi:error] [pid 26659] mod_wsgi (pid=26659): Failed to exec Python script file '/var/www/html/paper/src/paperless/wsgi.py'.
 [wsgi:error] [pid 26659]  mod_wsgi (pid=26659): Exception occurred processing WSGI script '/var/www/html/paper/src/paperless/wsgi.py'.
 [wsgi:error] [pid 26659] Traceback (most recent call last):
 [wsgi:error] [pid 26659]   File "/var/www/html/paper/src/paperless/wsgi.py", line 12, in <module>
 [wsgi:error] [pid 26659]    from django.core.wsgi import get_wsgi_application
 [wsgi:error] [pid 26659]   File "/var/www/html/paper/.env/lib/python3.7/site-packages/django/__init__.py", line 1, in <module>
[wsgi:error] [pid 26659]   from django.utils.version import get_version
[wsgi:error] [pid 26659] File "/var/www/html/paper/.env/lib/python3.7/site-packages/django/utils/version.py", line 1, in <module>
 [wsgi:error] [pid 26659]      import datetime
[wsgi:error] [pid 26659] File "/usr/lib/python3.7/datetime.py", line 8, in <module>
 [wsgi:error] [pid 26659]      import math as _math
 [wsgi:error] [pid 26659] ModuleNotFoundError: No module named 'math'
```

Any ideas for what I can try?

**Comment by GrahamDumpleton** [comment]
Was you virtual environment created from the system Python? Was the system Python upgrade since you created the virtual environment?

Don't think it is the issue, but you should alsouse:

```
WSGIDaemonProcess paperless user=r group=paperless threads=5 python-home=var/www/html/paper/.env python-path=/var/www/html/paper/src
```

That is, use `python-home` to specify the location of the virtual environment.

**Comment by RobertHosking** [comment]
The virtualenv was created with an older version of python. 
I have removed the `.env` folder and recreated it using python 3.7, installed packages, etc.
I also made the `python-home` adjustment in the apache config.

Still getting the same error after apache restart.

**Comment by RobertHosking** [comment]
I've given up trying to get it to work with my python3.7 installation. Trying again with Python3.5. Thanks anyways!

**Comment by belug23** [comment]
I had the same problem trying to use `python 3.8` with `mod_wsgi 4.6.8`.

Adding the `python-home` in the `WSGIDaemonProcess` config solved the problem.
