### ISSUE TITLE
Windows + Django + runmodwsgi : os.getuid() not supported on windows platforms

### ISSUE THREAD

**Issue by cizario** [GrahamDumpleton/mod_wsgi#466]
Windows 7
Python 3.7.3
Apache 2.4.23
Django 2.2.4

I'm trying to use `mod_wsgi` package in my Django project in order to server static assets locally, but when i run this command 

```
python manage.py runmodwsgi
```

i run into this error :

```
(hellodjango) c:\Python37\_apps\hellodjango>py manage.py runmodwsgi
Successfully ran command.

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()

  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)

  File "C:\Python37\_envs\hellodjango\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()

  File "C:\Python37\_envs\hellodjango\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "C:\Python37\_envs\hellodjango\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)

  File "C:\Python37\_envs\hellodjango\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)

  File "C:\Python37\_envs\hellodjango\lib\site-packages\mod_wsgi\server\management\commands\runmodwsgi.py", line 134, in handle
    'start-server', args, options)

  File "C:\Python37\_envs\hellodjango\lib\site-packages\mod_wsgi\server\__init__.py", line 2671, in _cmd_setup_server
    options['port'], os.getuid())

AttributeError: module 'os' has no attribute 'getuid'
```

it seems that `os.getuid()` is not supported on Windows platforms. Is there an other way to work arround ?

**Comment by GrahamDumpleton** [comment]
Although you can run `pip install mod_wsgi` on Windows, you cannot use `mod_wsgi-express start-server` or the Django management command integration. You will need to manually configure your Apache installation to load mod_wsgi and then configure Apache to host your Django application in similar manner to what Django documentation describes for mod_wsgi.

See notes about `mod_wsgi-express module-config` option in:

* https://pypi.org/project/mod-wsgi/

and:

* https://docs.djangoproject.com/en/2.2/howto/deployment/wsgi/modwsgi/

**Comment by cizario** [comment]
i already setup `mod_wsgi` with Apache on Windows for my Django project and it works perfectly.

since Django management commands of `mod_wsgi` package are not supported on windows platforms i close this thread.
