### ISSUE TITLE
ModuleNotFoundError: No module named 'mod_wsgi_packages'

### ISSUE THREAD

**Issue by apbti** [GrahamDumpleton/mod_wsgi#472]
Hello Graham,

I took control of an existing maintenance of a Django app running on a virtual linux machine with VMWare. Due to various version errors, I have decided to re-create the whole program on a new VMWare created server. After installing required modules and services, I created a new Django app, and just tried to run it on it's server after modifying apache2.conf and settings and received following error when trying to view from the ip page,

```
[Mon Oct 14 15:59:46.692228 2019] [wsgi:error] [pid 3447:tid 140430263973632] [client 172.16.1.160:57159] mod_wsgi (pid=3447): Target WSGI script '/home/test/xb_project/xlsx_bti/wsgi.py' cannot be loaded as Python module.
[Mon Oct 14 15:59:46.692357 2019] [wsgi:error] [pid 3447:tid 140430263973632] [client 172.16.1.160:57159] mod_wsgi (pid=3447): Exception occurred processing WSGI script '/home/test/xb_project/xlsx_bti/wsgi.py'.
[Mon Oct 14 15:59:46.692895 2019] [wsgi:error] [pid 3447:tid 140430263973632] [client 172.16.1.160:57159] Traceback (most recent call last):
[Mon Oct 14 15:59:46.692984 2019] [wsgi:error] [pid 3447:tid 140430263973632] [client 172.16.1.160:57159]   File "/home/test/xb_project/xlsx_bti/wsgi.py", line 12, in <module>
[Mon Oct 14 15:59:46.693010 2019] [wsgi:error] [pid 3447:tid 140430263973632] [client 172.16.1.160:57159]     from django.core.wsgi import get_wsgi_application
[Mon Oct 14 15:59:46.693074 2019] [wsgi:error] [pid 3447:tid 140430263973632] [client 172.16.1.160:57159] ModuleNotFoundError: No module named 'django'
```
After reading through, possibly every single Stackoverflow and others about ModuleNotFoundError: No module named 'django', I gave up trying to run it locally on the virtual server, and created a new project inside a virtual env, and after many hours of trial and error, I started receiving the same 'No module named 'django.' Then, I realized apxs_config.py file was different on the original program, so I copied it.

apxs_config.py
```
[import os

WITH_TARBALL_PACKAGE = False
WITH_HTTPD_PACKAGE = False

if WITH_HTTPD_PACKAGE:
    from mod_wsgi_packages.httpd import __file__ as PACKAGES_ROOTDIR
    PACKAGES_ROOTDIR = os.path.dirname(PACKAGES_ROOTDIR)
    BINDIR = os.path.join(PACKAGES_ROOTDIR, 'bin')
    SBINDIR = BINDIR
    LIBEXECDIR = os.path.join(PACKAGES_ROOTDIR, 'modules')
    SHLIBPATH = os.path.join(PACKAGES_ROOTDIR, 'lib')
elif WITH_TARBALL_PACKAGE:
    from mod_wsgi.packages import __file__ as PACKAGES_ROOTDIR
    PACKAGES_ROOTDIR = os.path.dirname(PACKAGES_ROOTDIR)
    BINDIR = os.path.join(PACKAGES_ROOTDIR, 'apache', 'bin')
    SBINDIR = BINDIR
    LIBEXECDIR = os.path.join(PACKAGES_ROOTDIR, 'apache', 'modules')
    SHLIBPATH = []
    SHLIBPATH.append(os.path.join(PACKAGES_ROOTDIR, 'apr-util', 'lib'))
    SHLIBPATH.append(os.path.join(PACKAGES_ROOTDIR, 'apr', 'lib'))
    SHLIBPATH = ':'.join(SHLIBPATH)
else:
    BINDIR = '/usr/bin'
    SBINDIR = '/usr/sbin'
    LIBEXECDIR = '/usr/lib/apache2/modules'
    SHLIBPATH = ''

MPM_NAME = ''
PROGNAME = 'apache2'
SHLIBPATH_VAR = 'LD_LIBRARY_PATH'

if os.path.exists(os.path.join(SBINDIR, PROGNAME)):
    HTTPD = os.path.join(SBINDIR, PROGNAME)
elif os.path.exists(os.path.join(BINDIR, PROGNAME)):
    HTTPD = os.path.join(BINDIR, PROGNAME)
else:
    HTTPD = PROGNAME

if os.path.exists(os.path.join(SBINDIR, 'rotatelogs')):
    ROTATELOGS = os.path.join(SBINDIR, 'rotatelogs')
elif os.path.exists(os.path.join(BINDIR, 'rotatelogs')):
    ROTATELOGS = os.path.join(BINDIR, 'rotatelogs')
else:
    ROTATELOGS = 'rotatelogs'](url)
```

and I started receiving the following error:
```
[[Mon Oct 14 22:51:45.259693 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185] mod_wsgi (pid=10685): Failed to exec Python script file '/home/test/xb/xb_project/xlsx_bti/wsgi.py'.
[Mon Oct 14 22:51:45.259873 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185] mod_wsgi (pid=10685): Exception occurred processing WSGI script '/home/test/xb/xb_project/xlsx_bti/wsgi.py'.
[Mon Oct 14 22:51:45.265030 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185] Traceback (most recent call last):
[Mon Oct 14 22:51:45.265134 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "/home/test/xb/venv/lib/python3.6/site-packages/django/apps/config.py", line 118, in create
[Mon Oct 14 22:51:45.265159 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]     cls = getattr(mod, cls_name)
[Mon Oct 14 22:51:45.265217 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185] AttributeError: module 'mod_wsgi' has no attribute 'server'
[Mon Oct 14 22:51:45.265261 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185] 
[Mon Oct 14 22:51:45.265279 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185] During handling of the above exception, another exception occurred:
[Mon Oct 14 22:51:45.265295 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185] 
[Mon Oct 14 22:51:45.265328 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185] Traceback (most recent call last):
[Mon Oct 14 22:51:45.265458 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "/home/test/xb/xb_project/xlsx_bti/wsgi.py", line 20, in <module>
[Mon Oct 14 22:51:45.265481 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]     application = get_wsgi_application()
[Mon Oct 14 22:51:45.265515 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "/home/test/xb/venv/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Mon Oct 14 22:51:45.265535 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]     django.setup(set_prefix=False)
[Mon Oct 14 22:51:45.265567 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "/home/test/xb/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
[Mon Oct 14 22:51:45.265586 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]     apps.populate(settings.INSTALLED_APPS)
[Mon Oct 14 22:51:45.265662 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "/home/test/xb/venv/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
[Mon Oct 14 22:51:45.265683 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]     app_config = AppConfig.create(entry)
[Mon Oct 14 22:51:45.265715 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "/home/test/xb/venv/lib/python3.6/site-packages/django/apps/config.py", line 123, in create
[Mon Oct 14 22:51:45.265733 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]     import_module(entry)
[Mon Oct 14 22:51:45.265765 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
[Mon Oct 14 22:51:45.265783 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]     return _bootstrap._gcd_import(name[level:], package, level)
[Mon Oct 14 22:51:45.265815 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Mon Oct 14 22:51:45.265849 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Mon Oct 14 22:51:45.265937 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
[Mon Oct 14 22:51:45.265980 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
[Mon Oct 14 22:51:45.266014 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[Mon Oct 14 22:51:45.266047 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Mon Oct 14 22:51:45.266081 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "/home/test/xb/venv/lib/python3.6/site-packages/mod_wsgi/server/__init__.py", line 25, in <module>
[Mon Oct 14 22:51:45.266100 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]     from . import apxs_config
[Mon Oct 14 22:51:45.266132 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]   File "/home/test/xb/venv/lib/python3.6/site-packages/mod_wsgi/server/apxs_config.py", line 8, in <module>
[Mon Oct 14 22:51:45.266150 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185]     from mod_wsgi_packages.httpd import __file__ as PACKAGES_ROOTDIR
[Mon Oct 14 22:51:45.266201 2019] [wsgi:error] [pid 10685:tid 140361770776320] [client 172.16.1.160:61185] ModuleNotFoundError: No module named 'mod_wsgi_packages'](url)
```

If I go back to default apxs_config.py, I get ModuleNotFoundError: No module named 'django' again.

Here is my other modified file:
apache2/mods-available/wsgi.load
```
[LoadModule wsgi_module "/home/test/xb/venv/lib/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-x86_64-linux-gnu.so"
WSGIPythonHome "/home/test/xb/venv"

WSGIPythonPath "/home/test/xb/xb_project"

WSGIScriptAlias / /home/test/xb/xb_project/xlsx_bti/wsgi.py

<Directory /home/test/xb/xb_project/xlsx_bti>
	<Files wsgi.py>
		Require all granted
	</Files>
</Directory>](url)
```

I have been struggling with this for couple weeks now. Let me know if there are any other information that needs sharing.

**Comment by GrahamDumpleton** [comment]
The `apxs_config.py` file should only really come into play if you are using `mod_wsgi-express` to run `Apache/mod_wsgi`, you aren't, as you are manually configuring Apache for mod_wsgi. That said, the `apxs_config.py` woudl come into play since appear to be using `mod_wsgi-express module-config` to generate the config to manually add to Apache config, to load the `mod_wsgi.so` file built by using `pip install mod_wsgi`.

If I had to guess, these are the possible problems.

* You have a prior `LoadModule wsgi_module` line which is loading a system version of mod_wsgi, or version from elsewhere. That mod_wsgi may be for different Python installation.

* The `/home/test/xb/venv` virtual environment doesn't actually have Django installed in it, or permissions in that package when installed don't allow reading by others.

You should not copy `apxs_config.py` from a different installation.

Check above, and most importantly, work out where `django` is installed. It must be in that virtual environment. It cannot be installed in a per user site packages using `--user` option to `pip`.

**Comment by apbti** [comment]
> You have a prior LoadModule wsgi_module line which is loading a system version of mod_wsgi, or version from elsewhere. That mod_wsgi may be for different Python installation.
How am I suppose to check for this? In my venv/lib, I only have python3.6. Could this still be the case if so?

> The /home/test/xb/venv virtual environment doesn't actually have Django installed in it, or permissions in that package when installed don't allow reading by others.
Sorry! but I don't follow 100%. I originally had Django Ver. 2.0.5 installed, and because I changed my mind, I got venv, and within venv, I did pip3 install django==2.0.5 again. So I have the django in
venv/lib/python3.6/site-packages/django

For reference,
Django==2.0.5
Python==3.6
mod_wsgi==4.6.8
Ubuntu 18.04
Apache 2.4.29

**Comment by GrahamDumpleton** [comment]
You need look through all the Apache config files looking for a line that has `LoadModule wsgi_module`. The Apache error log should also warning you if there are duplicate lines.

When you have the virtual environment activated for command line Python and run `python`, what do you get in the interpreter for:

```
import django
print(django.__file__)
```

What do you get when run run in a shell:

```
ls -las /home/test/xb/venv/lib/python3.6/site-packages
```

Do you have anywhere in your project area a file called `django.py` by chance?

Also ensure that you have at some point done a complete stop of Apache, and started it again, not just a reload, in case older mod_wsgi version hasn't been unmapped from the Apache processes properly.

**Comment by apbti** [comment]
When I activate Python by running `python3` and search for django.__file__, I get
`/home/test/xb/venv/lib/python3.6/site-packages/django/__init__.py`

When I look for permission of site-packages, I get
`4 drwxrwxr-x 45 test 4096 Oct 14 22:11 site-packages`

My current directory follows the most basic structure right now:
```
xb\
├── venv\
├── xb_project\
    ├── xlsx_bti
     |     ├── __pycache__\
     |     ├── __init__.py
     |     ├── settings.py
     |     ├── urls.py
     |     ├── wsgi.py
    ├── db.sqlite3
    └── manage.py
```
I don't seems to have a django.py in my project folder.

I am currently using the following after making any changes and checking the apache error log.
`sudo service apache2 restart`

**Comment by GrahamDumpleton** [comment]
Why are your code and config snippets above surrounded by `[...](url)`? You seem to be using it like that, which is wrong.

Also, are you also installing `mod_wsgi-httpd` instead of using your system Apache?

**Comment by apbti** [comment]
I think the (url) thing showed up when I tried to wrap it as a code snippet on Git, it is not something i copied and pasted from my code itself.

I am using the system apache.

**Comment by GrahamDumpleton** [comment]
The error `The requested URL / was not found on this server.` would likely indicate that your request isn't even being handled by the correct `VirtualHost` in the Apache configuration.

In other words it is falling back to using the default `VirtualHost`.

Part of the issue may be that you shouldn't just be throwing `WSGIScriptAlias` into the `wsgi.load` file. You should be using `VirtualHost`'s and it would be a part of one of those.
