### ISSUE TITLE
mod_wsgi (pid=6746): Target WSGI script '/home/user/project_name/restApi/service.wsgi' cannot be loaded as Python module.

### ISSUE THREAD

**Issue by dipakdas99** [GrahamDumpleton/mod_wsgi#486]
```
[Wed Nov 13 04:40:49.412171 2019] [:error] [pid 6746] [client 103.68.105.248:55749] mod_wsgi (pid=6746): Target WSGI script '/home/user/project_name/restApi/service.wsgi' cannot be loaded as Python module.
[Wed Nov 13 04:40:49.412223 2019] [:error] [pid 6746] [client 103.68.105.248:55749] mod_wsgi (pid=6746): Exception occurred processing WSGI script '/home/user/project_name/restApi/service.wsgi'.
[Wed Nov 13 04:40:49.412247 2019] [:error] [pid 6746] [client 103.68.105.248:55749] Traceback (most recent call last):
[Wed Nov 13 04:40:49.412268 2019] [:error] [pid 6746] [client 103.68.105.248:55749]   File "/home/user/project_name/restApi/service.wsgi", line 16, in <module>
[Wed Nov 13 04:40:49.412332 2019] [:error] [pid 6746] [client 103.68.105.248:55749]     from main import app as application
[Wed Nov 13 04:40:49.412340 2019] [:error] [pid 6746] [client 103.68.105.248:55749]   File "/home/user/project_name/restApi/main.py", line 27, in <module>
[Wed Nov 13 04:40:49.412387 2019] [:error] [pid 6746] [client 103.68.105.248:55749]     USERNAME = config.get(‘file’, 'Username')
[Wed Nov 13 04:40:49.412395 2019] [:error] [pid 6746] [client 103.68.105.248:55749]   File "/usr/lib64/python2.7/ConfigParser.py", line 330, in get
[Wed Nov 13 04:40:49.412607 2019] [:error] [pid 6746] [client 103.68.105.248:55749]     raise NoSectionError(section)
[Wed Nov 13 04:40:49.412643 2019] [:error] [pid 6746] [client 103.68.105.248:55749] NoSectionError: No section: ‘file’
```
Here is service.wsgi file

```
#!/usr/bin/env python
import sys
import logging

logging.basicConfig(stream=sys.stderr)

python_home = '/home/user/project_name/'

activate_this = python_home + '/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))

sys.path.insert(0, ‘/home/user/project_name/restApi/')

from main import app as application
application.secret_key = 'skodashboard'
```

Here is my `httpd.conf`

```
<VirtualHost *:80>
     # Add machine's IP address (use ifconfig command)
     ServerName 34.73.231.210
     # Give an alias to to start your website url with
     WSGIScriptAlias /api/v1/fileupload /home/user/project_name/restApi/service.wsgi
     <Directory /home/user/project_name/restApi/>
            # set permissions as per apache2.conf file
            Options FollowSymLinks
            AllowOverride None
            Require all granted
     </Directory>
     ErrorLog /var/log/system_error.log
     LogLevel warn
     CustomLog /var/log/access.log combined
</VirtualHost>

```
Here is my directory permission
```
0 drwxrwxrwx. 2 user user  136 Nov 13 04:53 .
0 drwxrwxr-x. 6 user user   82 Nov 13 03:05 ..
4 -rwxrwxr-x. 1 user user  271 Nov 11 10:12 check.py
4 -rw-r--r--. 1 user user  859 Nov 11 10:13 check.pyc
4 -rwxrwxr-x. 1 user    user     122 Nov  8 04:10 credential.properties
8 -rw-rw-r--. 1 user user 6148 Oct 30 02:35 .DS_Store
4 -rwxrwxr-x. 1 user    user    3322 Nov 13 03:58 main.py
4 -rw-r--r--. 1 apache  apache  3478 Nov 13 04:02 main.pyc
4 -rwxrwxr-x. 1 user    user     505 Nov 13 04:53 service.wsgi
```
Please help out as I am very new to python and apache mod_wsgi also.

**Comment by GrahamDumpleton** [comment]
This has nothing really to do with mod_wsgi. The error indicates that your config file doesn't have a section called ``file``.

The only way can see it be related to mod_wsgi is if you had given a relative path name to the config file and the code didn't error when it couldn't be found, and instead assumed there was no config file, and thus can't find setting.

See:

* https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#application-working-directory

about ensuring you are not using relative path names to files and are constructing full path names.

**Comment by dipakdas99** [comment]
Hi Graham,
Thanks for your reply

I've resolved that relative path issue.

while executing by `python /home/user/project_name/restApi/service.wsgi`  there is no section error

but while trying to access url 'http://34.73.252.246/api/v1/fileupload' i am getting below error

```
Wed Nov 13 05:16:23.269433 2019] [:error] [pid 7502] [client 65.155.30.101:24989] mod_wsgi (pid=7502): Target WSGI script '/home/user/project_name/restApi/service.wsgi' cannot be loaded as Python module., referer: http://www.bing.com/search?q=amazon
[Wed Nov 13 05:16:23.269485 2019] [:error] [pid 7502] [client 65.155.30.101:24989] mod_wsgi (pid=7502): Exception occurred processing WSGI script '/home/user/project_name/restApi/service.wsgi'., referer: http://www.bing.com/search?q=amazon
[Wed Nov 13 05:16:23.269526 2019] [:error] [pid 7502] [client 65.155.30.101:24989] Traceback (most recent call last):, referer: http://www.bing.com/search?q=amazon
[Wed Nov 13 05:16:23.269551 2019] [:error] [pid 7502] [client 65.155.30.101:24989]   File "/home/user/project_name/restApi/service.wsgi", line 16, in <module>, referer: http://www.bing.com/search?q=amazon
[Wed Nov 13 05:16:23.269622 2019] [:error] [pid 7502] [client 65.155.30.101:24989]     from main import app as application, referer: http://www.bing.com/search?q=amazon
[Wed Nov 13 05:16:23.269630 2019] [:error] [pid 7502] [client 65.155.30.101:24989]   File "/home/user/project_name/restApi/main.py", line 27, in <module>, referer: http://www.bing.com/search?q=amazon
[Wed Nov 13 05:16:23.269679 2019] [:error] [pid 7502] [client 65.155.30.101:24989]     USERNAME = config.get(‘file’, 'Username'), referer: http://www.bing.com/search?q=amazon
[Wed Nov 13 05:16:23.269687 2019] [:error] [pid 7502] [client 65.155.30.101:24989]   File "/usr/lib64/python2.7/ConfigParser.py", line 330, in get, referer: http://www.bing.com/search?q=amazon
[Wed Nov 13 05:16:23.269873 2019] [:error] [pid 7502] [client 65.155.30.101:24989]     raise NoSectionError(section), referer: http://www.bing.com/search?q=amazon
[Wed Nov 13 05:16:23.269904 2019] [:error] [pid 7502] [client 65.155.30.101:24989] NoSectionError: No section: ‘file’, referer: http://www.bing.com/search?q=amazon
```
Even though I have changed the section name `file` to `file1` stil it is poing to old one. is it python path issue?

my flask app is running perfectly by executing `sudo python main.py`.

My apologies if haven't explain you properly.

**Comment by GrahamDumpleton** [comment]
Did you restart Apache? It doesn't automatically reload code.

Read:

* https://modwsgi.readthedocs.io/en/develop/user-guides/reloading-source-code.html

and make sure you are using recommended daemon mode if you aren't already as it better to do so.

**Comment by dipakdas99** [comment]
I am not getting any error now by follow your guidelines but I am getting response as `404`
postman response
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try
	again.</p>
``` 
URL : `http://34.73.231.210/api/v1/fileupload`
The same URL if I try using the command `sudo python main.py` i can able to upload the file into my server
After starting the apache server I am getting the above response.

Do I need to change `httpd.conf` file? I have no clue how to do that.

Thanks for your help. Much appreciated

**Comment by GrahamDumpleton** [comment]
If you are defining the full route path in the WSGI application, you should not be using `/api/v1/fileupload` with `WSGIScriptAlias`, you should be using just `/`.

The URL you should use is whatever is supplied to `WSGIScriptAlias` plus the route in the WSGI application.

If you can't have it at the root of the web site, use:

```
WSGIScriptAlias /myapp /home/user/project_name/restApi/service.wsgi
```

and then use a URL of:

```
http://34.73.231.210/myappy/api/v1/fileupload
```

Note that your WSGI application shouldn't hard code absolute paths when doing redirects etc, use whatever the web framework you are using provides to construct URLs, as it will add in the mount path used (ie., /myapp) for you automatically.

**Comment by dipakdas99** [comment]
Thank you so much. You made my day.

**Comment by GrahamDumpleton** [comment]
I'll assume I have solved your issue and will close this then.
