### ISSUE TITLE
IOError: [Errno 13] Permission denied: '/home/user/extracts/nuschool_archive/nuschool_instance.zip'

### ISSUE THREAD

**Issue by dipakdas99** [GrahamDumpleton/mod_wsgi#489]
I have been trying to save the zip file a directory using python 2.7, but getting as `IOError: [Errno 13] Permission denied` error although I have `777` permission of that directory.
```
[Fri Nov 15 05:02:30.126412 2019] [:error] [pid 16556] ERROR:main:Exception on /v1/fileupload [POST]
[Fri Nov 15 05:02:30.126481 2019] [:error] [pid 16556] Traceback (most recent call last):
[Fri Nov 15 05:02:30.126484 2019] [:error] [pid 16556]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
[Fri Nov 15 05:02:30.126487 2019] [:error] [pid 16556]     response = self.full_dispatch_request()
[Fri Nov 15 05:02:30.126499 2019] [:error] [pid 16556]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
[Fri Nov 15 05:02:30.126502 2019] [:error] [pid 16556]     rv = self.handle_user_exception(e)
[Fri Nov 15 05:02:30.126504 2019] [:error] [pid 16556]   File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
[Fri Nov 15 05:02:30.126506 2019] [:error] [pid 16556]     return original_handler(e)
[Fri Nov 15 05:02:30.126507 2019] [:error] [pid 16556]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
[Fri Nov 15 05:02:30.126509 2019] [:error] [pid 16556]     reraise(exc_type, exc_value, tb)
[Fri Nov 15 05:02:30.126511 2019] [:error] [pid 16556]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
[Fri Nov 15 05:02:30.126513 2019] [:error] [pid 16556]     rv = self.dispatch_request()
[Fri Nov 15 05:02:30.126515 2019] [:error] [pid 16556]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
[Fri Nov 15 05:02:30.126517 2019] [:error] [pid 16556]     return self.view_functions[rule.endpoint](**req.view_args)
[Fri Nov 15 05:02:30.126520 2019] [:error] [pid 16556]   File "/usr/lib/python2.7/site-packages/flask_httpauth.py", line 105, in decorated
[Fri Nov 15 05:02:30.126522 2019] [:error] [pid 16556]     return f(*args, **kwargs)
[Fri Nov 15 05:02:30.126523 2019] [:error] [pid 16556]   File "/home/user/project_name/src/restApi/main.py", line 59, in upload_file
[Fri Nov 15 05:02:30.126525 2019] [:error] [pid 16556]     file.save(os.path.join(UPLOAD_FOLDER, filename))
[Fri Nov 15 05:02:30.126527 2019] [:error] [pid 16556]   File "/usr/lib/python2.7/site-packages/werkzeug/datastructures.py", line 2800, in save
[Fri Nov 15 05:02:30.126529 2019] [:error] [pid 16556]     dst = open(dst, "wb")
[Fri Nov 15 05:02:30.126531 2019] [:error] [pid 16556] IOError: [Errno 13] Permission denied: '/home/user/extracts/nuschool_archive/nuschool_instance.zip'
```
here is my directory permission:
```
drwxrwxrwx. 3 user   user        88 Nov 15 05:02: extracts

drwxrwxrwx. 2 user user       34 Nov 15 05:02: nuschool_archive
```
If I execute  by `sudo python main.py` I can able to upload the file. After configured in `apache mod_wsgi` getting permission issue

here is my `httpd.conf`
```
<VirtualHost *:80>
     # Add machine's IP address (use ifconfig command)
     ServerName 35.145.111.117
     # Give an alias to to start your website url with
     WSGIScriptAlias /api /home/user/project_name/src/restApi/service.wsgi
     WSGIPassAuthorization On
     WSGIDaemonProcess /api
     WSGIProcessGroup /api
     <Directory /home/user/project_name/src/restApi/>
            # set permissions as per apache2.conf file
            #Options FollowSymLinks
            #AllowOverride None
            Require all granted
     </Directory>
     ErrorLog /var/log/system_error.log
     LogLevel warn
     CustomLog /var/log/access.log combined
</VirtualHost>
```

**Comment by GrahamDumpleton** [comment]
Does the Apache user have directory access to all the directories in the path ``/home/user/extracts/nuschool_archive``? Not just the last directory.

Are you running CentOS/RHEL with SELinux enabled, or Debian/Ubuntu with AppArmor. These might be configured to prevent the Apache user writing to the directory.

**Comment by dipakdas99** [comment]
I have `user` permission (777) to '/home/user/extract/nuschool_archive/'.
yes I am using CentOS 7. I have enabled SELinux to `SELINUX=enforcing`. same error persisting

**Comment by GrahamDumpleton** [comment]
I said "all the directories in the path". What are permissions on:

* `/home/user/extracts`
* `/home/user`

My understanding is that `enforcing` is what turns SELinux on. If that is what you had, temporarily change it to `permissive` and restart Apache. If that then works, you will need to change it back to `enforcing` and configure SELinux to allow Apache to write to the directory.

**Comment by dipakdas99** [comment]
```
drwxrwxrwx. 11 user user 270 Nov 15 05:01 /home/user
drwxrwxrwx. 3 user user 88 Nov 15 05:01 /home/user/extracts/
drwxrwxr-x. 2 user user 6 Nov 15 05:01 /home/user/extracts/nuschool_archive
```
I have changed `enforcing ` to `permissive `. still same error.

**Comment by GrahamDumpleton** [comment]
Was this always:

```
drwxrwxr-x. 2 user user 6 Nov 15 05:01 /home/user/extracts/nuschool_archive
```

You previously said was `drwxrwxrwx`.

Without that last `w` Apache user can't write to that directory.

Anyway, better not to be giving write access to others. Instead try:

```
WSGIDaemonProcess /api user=xxx group=yyy
```

Replacing `xxx` with your user name, and `yyy` with the group for your user.

**Comment by dipakdas99** [comment]
I am extremely sorry for that Graham. Now the issue has solved. Thank you so much for your help.
