### ISSUE TITLE
using WSGIScriptAlias, in http.conf throwing an error.

### ISSUE THREAD

**Issue by bandatarunkumar** [GrahamDumpleton/mod_wsgi#555]
Hi Graham,

i have used mod_wsgi module for loading python files, when i use WSGIScriptAlias in htttp.conf, the below error is getting thrown in ssl_error. Could you please help me in finding the root cause? 

WSGIScriptAlias / "/var/www/wsgi-scripts/wsgiapp.py"
WSGIPythonPath  "/var/www/wsgi-scripts/"

i have given execute permission for all the python scripts under the above path,

the browser is throwing 500 server error. Whenever i reload the url, the below httpd ssl-error are getting written,

```
 mod_wsgi (pid=104012): Target WSGI script '/var/www/wsgi-scripts/wsgiapp.py' cannot be loaded as Python module.
mod_wsgi (pid=104012): Exception occurred processing WSGI script '/var/www/wsgi-scripts/wsgiapp.py'.
Traceback (most recent call last):
File "/var/www/wsgi-scripts/wsgiapp.py", line 2, in <module>
  import cherrypy
File "/usr/lib/python2.7/site-packages/cherrypy/__init__.py", line 60, in <module>
   import pkg_resources
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
  @_call_aside
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
  f(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
   working_set = WorkingSet._build_master()
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
  ws = cls()
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 567, in __init__
  self.add_entry(entry)
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 623, in add_entry
  for dist in find_distributions(entry, True):
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2065, in find_on_path
  for dist in factory(fullpath):
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2127, in distributions_from_metadata
    if len(os.listdir(path)) == 0:
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/zc.lockfile-2.0.dist-info'
```

Thanks,
Tarun

**Comment by GrahamDumpleton** [comment]
Looks like you installed some packages as root where root had a restrictive umask at the time. As a result the directory permissions in the Python installation are now such that non root users can't read directories/files.

You should as root ``pip uninstall`` the affect package(s). Then reinstall them as root, but make sure the umask for root is set as 0755 and not something more restrictive such as 0700 as that will cause problems.

**Comment by bandatarunkumar** [comment]
Thanks Graham. i will try the same.

**Comment by bandatarunkumar** [comment]
Hi Graham,

Thanks for sharing your inputs, i am able to solve the issue by reinstalling by setting a umask.
