### ISSUE TITLE
Unable to run Django 2.1.15 WSGI with apache2

### ISSUE THREAD

**Issue by nkovacne** [GrahamDumpleton/mod_wsgi#562]
This apache 2.4 and libapache2-mod-wsgi-py3 on an Ubuntu 18.04 server.

I configured my apache site like this:

```
WSGIPythonHome "/opt/django/checklist/venv"
WSGIScriptAlias / /opt/django/checklist/checklist/checklist/wsgi.py
WSGIPythonPath "/opt/django/checklist/venv/bin/python3.6"

<VirtualHost *:80>
  DocumentRoot /opt/django/checklist/checklist

  <Directory /opt/django/checklist/checklist>
    Require all granted
    <Files wsgi.py>
      Require all granted
    </Files>
  </Directory>

  Alias /static/ /opt/django/checklist/checklist/static/
  <Directory /opt/django/checklist/checklist/static/>
    Require all granted
  </Directory>

  ErrorLog ${APACHE_LOG_DIR}/checklist.error.log
  CustomLog ${APACHE_LOG_DIR}/checklist.access.log combined
</VirtualHost>
```

The virtualenv was created like this:

```
root@X:/opt/django/checklist# virtualenv -p python3 venv
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /opt/django/checklist/venv/bin/python3
Also creating executable in /opt/django/checklist/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

root@X:/opt/django/checklist# . venv/bin/activate

(venv) root@X:/opt/django/checklist# pip install Django==2.1.*
Collecting Django==2.1.*
  Using cached Django-2.1.15-py3-none-any.whl (7.3 MB)
Collecting pytz
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Installing collected packages: pytz, Django
Successfully installed Django-2.1.15 pytz-2019.3
```

However, when running the app from a browser, this exception occurs:

```
mod_wsgi (pid=853): Target WSGI script '/opt/django/checklist/checklist/checklist/wsgi.py' cannot be loaded as Python module.
mod_wsgi (pid=853): Exception occurred processing WSGI script '/opt/django/checklist/checklist/checklist/wsgi.py'.
Traceback (most recent call last):
  File "/opt/django/checklist/checklist/checklist/wsgi.py", line 16, in <module>  
    application = get_wsgi_application()
  File "/opt/django/checklist/venv/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/opt/django/checklist/venv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/opt/django/checklist/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/opt/django/checklist/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/django/checklist/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/django/checklist/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'checklist'
```

All permissions were set to `www-data` and added execution permissions on `wsgy.py`.

There must be something very obvious I'm missing, but I can't seem to find what's missing. The app has no content so far. Could you please help?

**Comment by nkovacne** [comment]
Additional info:

```
>>> import sys
>>> print(sys.prefix)
/opt/django/checklist/venv
>>> import django
>>> print(django.__file__)
/opt/django/checklist/venv/lib/python3.6/site-packages/django/__init__.py
```

**Comment by GrahamDumpleton** [comment]
``WSGIPythonPath`` is not meant to be set to the path to the Python executable, but any directories from which modules need to be imported. For Django that should be the parent directory of the project.

Thus for what appears to be your setup:

```
WSGIPythonPath /opt/django/checklist/checklist
```

Check the various documentation on setting up Django and virtual environments.

* https://docs.djangoproject.com/en/3.0/howto/deployment/wsgi/modwsgi/
* https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

You should also consider using daemon mode of mod_wsgi, it is the recommended setup.

**Comment by nkovacne** [comment]
Indeed, that fixed it. My fault for assuming that was the Python path. Thanks a lot for the help and the good job.
