### ISSUE TITLE
mod_wsgi-express ModuleNotFoundError: No module named <insert module name>

### ISSUE THREAD

**Issue by genghisken** [GrahamDumpleton/mod_wsgi#591]
Hi Graham

I've been a fan of mod_wsgi (under Anaconda) for years, but I've always deployed my apps with the standard apache setup (complete with apache config file).  Since I now need to deploy both Python 2 and Python 3 apps from the same server, I figured that mod_wsgi-express was the way to go (with a bit of internal proxying from the main apache instance).

However, I can't get it to recognise my app.  It's a completely bog standard, default Django app called 'nameserver'.  It works fine under the Django development server (`python manage.py runserver`).

I've tried your default instructions and various combinations of stuff I googled, but still no joy deploying the webserver (on Mac OSX Catalina & Python 3.8 (Anaconda environment) + Django 3.0.7.  I can get the default wsgi server welcome page up and running, but I'm faced with an Internal Server Error when trying to use my app.  The log states:

```
[Thu Jul 16 10:09:18.351290 2020] [mpm_event:notice] [pid 5277:tid 4687842752] AH00489: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.8 configured -- resuming normal operations
[Thu Jul 16 10:09:18.351584 2020] [core:notice] [pid 5277:tid 4687842752] AH00094: Command line: 'httpd (mod_wsgi-express)  -f /var/tmp/mod_wsgi-localhost:8000:502/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D MOD_WSGI_LOAD_PYTHON_DYLIB -D FOREGROUND'
[Thu Jul 16 10:09:18.423503 2020] [wsgi:error] [pid 5282:tid 4687842752] mod_wsgi (pid=5282): Failed to exec Python script file '/var/tmp/mod_wsgi-localhost:8000:502/handler.wsgi'.
[Thu Jul 16 10:09:18.423665 2020] [wsgi:error] [pid 5282:tid 4687842752] mod_wsgi (pid=5282): Exception occurred processing WSGI script '/var/tmp/mod_wsgi-localhost:8000:502/handler.wsgi'.
[Thu Jul 16 10:09:18.424375 2020] [wsgi:error] [pid 5282:tid 4687842752] Traceback (most recent call last):
[Thu Jul 16 10:09:18.424406 2020] [wsgi:error] [pid 5282:tid 4687842752]   File "/var/tmp/mod_wsgi-localhost:8000:502/handler.wsgi", line 89, in <module>
[Thu Jul 16 10:09:18.424415 2020] [wsgi:error] [pid 5282:tid 4687842752]     handler = mod_wsgi.server.ApplicationHandler(entry_point,
[Thu Jul 16 10:09:18.424425 2020] [wsgi:error] [pid 5282:tid 4687842752]   File "/Users/kws/opt/anaconda3/envs/python3_code_test/lib/python3.8/site-packages/mod_wsgi/server/__init__.py", line 1404, in __init__
[Thu Jul 16 10:09:18.424432 2020] [wsgi:error] [pid 5282:tid 4687842752]     __import__(entry_point)
[Thu Jul 16 10:09:18.424449 2020] [wsgi:error] [pid 5282:tid 4687842752] ModuleNotFoundError: No module named 'nameserver'
[Thu Jul 16 10:09:23.928541 2020] [wsgi:error] [pid 5282:tid 123145349910528] [remote ::1:50020] mod_wsgi (pid=5282): Failed to exec Python script file '/var/tmp/mod_wsgi-localhost:8000:502/handler.wsgi'.
[Thu Jul 16 10:09:23.928718 2020] [wsgi:error] [pid 5282:tid 123145349910528] [remote ::1:50020] mod_wsgi (pid=5282): Exception occurred processing WSGI script '/var/tmp/mod_wsgi-localhost:8000:502/handler.wsgi'.
[Thu Jul 16 10:09:23.928821 2020] [wsgi:error] [pid 5282:tid 123145349910528] [remote ::1:50020] Traceback (most recent call last):
[Thu Jul 16 10:09:23.928860 2020] [wsgi:error] [pid 5282:tid 123145349910528] [remote ::1:50020]   File "/var/tmp/mod_wsgi-localhost:8000:502/handler.wsgi", line 89, in <module>
[Thu Jul 16 10:09:23.928872 2020] [wsgi:error] [pid 5282:tid 123145349910528] [remote ::1:50020]     handler = mod_wsgi.server.ApplicationHandler(entry_point,
[Thu Jul 16 10:09:23.928885 2020] [wsgi:error] [pid 5282:tid 123145349910528] [remote ::1:50020]   File "/Users/kws/opt/anaconda3/envs/python3_code_test/lib/python3.8/site-packages/mod_wsgi/server/__init__.py", line 1404, in __init__
[Thu Jul 16 10:09:23.928894 2020] [wsgi:error] [pid 5282:tid 123145349910528] [remote ::1:50020]     __import__(entry_point)
[Thu Jul 16 10:09:23.928912 2020] [wsgi:error] [pid 5282:tid 123145349910528] [remote ::1:50020] ModuleNotFoundError: No module named 'nameserver'
[Thu Jul 16 10:09:28.794594 2020] [mpm_event:notice] [pid 5277:tid 4687842752] AH00491: caught SIGTERM, shutting down
```

Startup script is either:
```
mod_wsgi-express start-server --working-directory nameserver --url-alias /static static --application-type module nameserver.wsgi
```

or (from top nameserver directory)
```
mod_wsgi-express start-server --url-alias /static static --application-type module nameserver.wsgi
```
or

```
python manage.py runmodwsgi
```

All give the error above.

Relevant settings.py entries:
```
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nameserver',
    'nameserverapi.apps.NameserverapiConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'django_tables2',
    'mod_wsgi.server',
]

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
```

Contents of wsgi.py - completely bog standard - no changes

```
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'nameserver.settings')

application = get_wsgi_application()
```

I also tried adding in

```
import sys
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(BASE_DIR)
os.environ['DJANGO_SETTINGS_MODULE'] = 'nameserver.settings'
```

But still no joy - same error message.  I've spent many hours trying to figure this out.  Any ideas what I'm doing wrong??  I'm sure it's something trivial, but I really can't see what's up.

**Comment by GrahamDumpleton** [comment]
You are possible in the wrong directory. Try the method explained in:

* http://blog.dscpl.com.au/2015/04/integrating-modwsgi-express-as-django.html

Otherwise you need to probably describe your directory structure and where ``wsgi.py`` file is, plus where you are running from.

**Comment by GrahamDumpleton** [comment]
My bad, you are following that. Explain your directory structure, especially whether you have change your ``settings.py`` file to use a sub directory etc.

**Comment by GrahamDumpleton** [comment]
So provide a ``ls -R`` directory listing starting at directory above project directory and indicate which settings file sets ``BASE_DIR`` so can understand what it is being set to. Trim out garbage from directory listing. Key things is knowing where settings and wsgi.py files are, and names of top level and project directories.

**Comment by genghisken** [comment]
OK. I think the results of find are more readable.  This is the project structure.

```
(python3_code_test) kws::148918arcksmith { ~/Documents/code/gitdev/gknames/nameserver }-> pwd

/Users/kws/Documents/code/gitdev/gknames/nameserver

(python3_code_test) kws::148918arcksmith { ~/Documents/code/gitdev/gknames/nameserver }-> find . <blah blah>

.
./nameserverapi
./nameserverapi/serializers.py
./nameserverapi/__init__.py
./nameserverapi/apps.py
./nameserverapi/admin.py
./nameserverapi/tests.py
./nameserverapi/urls.py
./nameserverapi/tsvToJSON.py
./nameserverapi/views.py
./nameserver
./nameserver/models.py
./nameserver/asgi.py
./nameserver/__init__.py
./nameserver/settings.py
./nameserver/templates
./nameserver/templates/events_old.html
./nameserver/templates/base_bootstrap.html
./nameserver/templates/events.html
./nameserver/urls.py
./nameserver/views.py
./nameserver/wsgi.py
./manage.py
```

**Comment by genghisken** [comment]
Ignore the extra stuff I added into wsgi.py above.  The BASE_DIR is set in settings.py as above.

```
(python3_code_test) kws::148918arcksmith { ~/Documents/code/gitdev/gknames/nameserver }-> python manage.py shell
Python 3.8.2 (default, May  6 2020, 02:49:43) 
[Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from settings import BASE_DIR
>>> print(BASE_DIR)
/Users/kws/Documents/code/gitdev/gknames/nameserver
```

**Comment by genghisken** [comment]
Well, here's an interesting development... The one combination I hadn't tried.  I uninstalled mod_wsgi, and installed mod_wsgi-standalone.  Eureka, everything works.  Looks like it's not happy with the system apache.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
