### ISSUE TITLE
wsgi error: fails to configure a file logger

### ISSUE THREAD

**Issue by tksundar** [GrahamDumpleton/mod_wsgi#609]
Here is the logging config in settings.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {asctime} {module} - {message}',
            'style': '{'
        }
    },
    'handlers': {
        'stream': {
            'level': 'DEBUG',
            'class': 'logging.',
            'formatter': 'simple',

        },
        'file-ffl': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'simple',
            'filename': 'c:/dev/ffl/log/debug.log'

        }
    },
    'loggers': {
        'sorl.thumbnail': {
            'handlers': ['stream', ],
            'level': 'DEBUG',
            'propagate': True
        },
        'ffl': {
            'handlers': ['file-ffl'],
            'level': 'DEBUG',
            'propagate': True
        }

    }
}
-----------------------------------------------------------------------------------------------------
the error log output is given below:

[Sat Aug 29 16:05:41.478798 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091] mod_wsgi (pid=6760): Failed to exec Python script file 'C:/dev1/ffl/ffl/wsgi.py'.
[Sat Aug 29 16:05:41.478798 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091] mod_wsgi (pid=6760): Exception occurred processing WSGI script 'C:/dev1/ffl/ffl/wsgi.py'.
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091] Traceback (most recent call last):\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]   File "C:\\Apps\\Python37\\Lib\\logging\\config.py", line 563, in configure\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]     handler = self.configure_handler(handlers[name])\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]   File "C:\\Apps\\Python37\\Lib\\logging\\config.py", line 736, in configure_handler\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]     result = factory(**kwargs)\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]   File "C:\\Apps\\Python37\\Lib\\logging\\__init__.py", line 1087, in __init__\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]     StreamHandler.__init__(self, self._open())\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]   File "C:\\Apps\\Python37\\Lib\\logging\\__init__.py", line 1116, in _open\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]     return open(self.baseFilename, self.mode, encoding=self.encoding)\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091] FileNotFoundError: [Errno 2] No such file or directory: 'c:\\\\dev\\\\ffl\\\\log\\\\debug.log'\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091] \r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091] The above exception was the direct cause of the following exception:\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091] \r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091] Traceback (most recent call last):\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]   File "C:/dev1/ffl/ffl/wsgi.py", line 16, in <module>\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]     application = get_wsgi_application()\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]   File "c:\\dev1\\ffl\\venv\\Lib\\site-packages\\django\\core\\wsgi.py", line 12, in get_wsgi_application\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]     django.setup(set_prefix=False)\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]   File "c:\\dev1\\ffl\\venv\\Lib\\site-packages\\django\\__init__.py", line 19, in setup\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]   File "c:\\dev1\\ffl\\venv\\Lib\\site-packages\\django\\utils\\log.py", line 75, in configure_logging\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]     logging_config_func(logging_settings)\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]   File "C:\\Apps\\Python37\\Lib\\logging\\config.py", line 800, in dictConfig\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]     dictConfigClass(config).configure()\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]   File "C:\\Apps\\Python37\\Lib\\logging\\config.py", line 571, in configure\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091]     '%r' % name) from e\r
[Sat Aug 29 16:05:41.479828 2020] [wsgi:error] [pid 6760:tid 1160] [client ::1:60091] ValueError: Unable to configure handler 'file-ffl'\r

---------------------------------------------------------------------------------------

Anything wrong with the logging config? If I remove file logging, everything works. Thanks in advance.

**Comment by tksundar** [comment]
I fixed this. Now it starts fine. But nothing is logged to the created log file. All application log statements are in apache logs. Probably a config thing. I will dig
