### ISSUE TITLE
ImportError: No module named 'django' - mod-wsgi

### ISSUE THREAD

**Issue by alperencapar** [GrahamDumpleton/mod_wsgi#636]
i'm trying to deploy a website on VPS. Before everything, i was having python version problem. The problem was not let me to install up to date Django version. After that i updated python version. I did some test on port 8000 with venv and app was working. After the test, did setup up Apache2. Right now it showing 500 Internal Server Error. I believe this is python version error

I am adding some information that I think will be useful to identify the problem.

I'll be so grateful and happy if you help me

username: alpcusta
app located /home/alpcusta/diricangrup
venv located /home/alpcusta/venv

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial
```

```
sudo tail -f /var/log/apache2/error.log
[Wed Dec 09 19:40:47.256679 2020] [wsgi:error] [pid 12988:tid 140715055720192] [remote]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Wed Dec 09 19:40:47.256710 2020] [wsgi:error] [pid 12988:tid 140715055720192] [remote]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Wed Dec 09 19:40:47.256741 2020] [wsgi:error] [pid 12988:tid 140715055720192] [remote]   File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
[Wed Dec 09 19:40:47.256802 2020] [wsgi:error] [pid 12988:tid 140715055720192] [remote] ImportError: No module named 'django_cleanup'
[Wed Dec 09 11:44:23.763582 2020] [mpm_event:notice] [pid 9201:tid 140715168180096] AH00493: SIGUSR1 received.  Doing graceful restart
[Wed Dec 09 11:44:23.961788 2020] [mpm_event:notice] [pid 9201:tid 140715168180096] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/3.5.2 configured -- resuming normal operations
[Wed Dec 09 11:44:23.961829 2020] [core:notice] [pid 9201:tid 140715168180096] AH00094: Command line: '/usr/sbin/apache2'
[Wed Dec 09 11:44:24.207944 2020] [mpm_event:notice] [pid 9201:tid 140715168180096] AH00493: SIGUSR1 received.  Doing graceful restart
[Wed Dec 09 11:44:24.271115 2020] [mpm_event:notice] [pid 9201:tid 140715168180096] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/3.5.2 configured -- resuming normal operations
[Wed Dec 09 11:44:24.271147 2020] [core:notice] [pid 9201:tid 140715168180096] AH00094: Command line: '/usr/sbin/apache2'
[Wed Dec 09 11:44:37.716931 2020] [wsgi:error] [pid 13274:tid 140715034461952] [remote] mod_wsgi (pid=13274): Target WSGI script '/home/alpcusta/diricangrup/diricangrup/wsgi.py' cannot be loaded as Python module.
[Wed Dec 09 11:44:37.717065 2020] [wsgi:error] [pid 13274:tid 140715034461952] [remote] mod_wsgi (pid=13274): Exception occurred processing WSGI script '/home/alpcusta/diricangrup/diricangrup/wsgi.py'.
[Wed Dec 09 11:44:37.717375 2020] [wsgi:error] [pid 13274:tid 140715034461952] [remote] Traceback (most recent call last):
[Wed Dec 09 11:44:37.717431 2020] [wsgi:error] [pid 13274:tid 140715034461952] [remote]   File "/home/alpcusta/diricangrup/diricangrup/wsgi.py", line 2, in <module>
[Wed Dec 09 11:44:37.717456 2020] [wsgi:error] [pid 13274:tid 140715034461952] [remote]     from django.core.wsgi import get_wsgi_application
[Wed Dec 09 11:44:37.717498 2020] [wsgi:error] [pid 13274:tid 140715034461952] [remote] ImportError: No module named 'django'

apache2ctl configtest
Syntax OK
```

```
alpcusta@diricangrup:~$ python -V
Python 3.8.6
alpcusta@diricangrup:~$ python3 -V
Python 3.8.6
```

```
sudo journalctl -xe
Dec 09 12:06:02 diricangrup systemd[1]: Reloading LSB: Apache2 web server.
-- Subject: Unit apache2.service has begun reloading its configuration
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit apache2.service has begun reloading its configuration
Dec 09 12:06:02 diricangrup apache2[13500]:  * Reloading Apache httpd web server apache2
Dec 09 12:06:02 diricangrup apache2[13500]:  *
Dec 09 12:06:02 diricangrup systemd[1]: Reloaded LSB: Apache2 web server.
-- Subject: Unit apache2.service has finished reloading its configuration
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit apache2.service has finished reloading its configuration
--
-- The result is done.
```

/etc/apache2/sites-available/**diricangrup.conf**

```
<VirtualHost *:80>
        ServerName www.diricangrup.com
        ServerAlias *.diricangrup.com
        ServerAdmin webmaster@localhost
        DocumentRoot /home/alpcusta/diricangrup

        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined


        Alias /robots.txt /home/alpcusta/diricangrup/staticfiles/robots.txt
        Alias /favicon.ico /home/alpcusta/diricangrup/staticfiles/favicon.ico


        <Directory /home/alpcusta/diricangrup>
                Require all granted
                AllowOverride All
        </Directory>


        Alias /static /home/alpcusta/diricangrup/staticfiles
        <Directory /home/alpcusta/diricangrup/staticfiles>
                Require all granted
        </Directory>

        Alias /media /home/alpcusta/diricangrup/media
        <Directory /home/alpcusta/diricangrup/media>
                Require all granted
        </Directory>

        <Directory /home/alpcusta/diricangrup/diricangrup>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>


        WSGIScriptAlias / /home/alpcusta/diricangrup/diricangrup/wsgi.py
        WSGIDaemonProcess diricangrup.com python-path=/home/alpcusta/diricangrup python-home=/home/alpcusta/venv
        WSGIProcessGroup diricangrup.com



</VirtualHost>
```

**wsgi.py**
```
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'diricangrup.settings')

application = get_wsgi_application()
```

Modules

```
(venv) alpcusta@diricangrup:~$ pip freeze
asgiref==3.3.1
Django==3.1.3
django-cleanup==5.1.0
Pillow==8.0.1
pytz==2020.4
sqlparse==0.4.1
```

```
alpcusta@diricangrup:~$ tree -d  diricangrup/
diricangrup/
|-- contact
|   |-- __pycache__
|   `-- migrations
|       `-- __pycache__
|-- diricangrup
|   `-- __pycache__
|-- media
|-- references
|   |-- __pycache__
|   `-- migrations
|       `-- __pycache__
|-- static
|   |-- css
|   |-- img
|   |-- js
|   `-- svg
|-- staticfiles
|   |-- admin
|   |   |-- css
|   |   |   `-- vendor
|   |   |       `-- select2
|   |   |-- fonts
|   |   |-- img
|   |   |   `-- gis
|   |   `-- js
|   |       |-- admin
|   |       `-- vendor
|   |           |-- jquery
|   |           |-- select2
|   |           |   `-- i18n
|   |           `-- xregexp
|   |-- css
|   |-- img
![Screenshot_1](https://user-images.githubusercontent.com/32480268/101663716-18a80980-3a5c-11eb-97fd-715bd28cf253.png)

|   |-- js
|   `-- svg
`-- templates
    `-- includes
```

**Comment by GrahamDumpleton** [comment]
As the Apache logs indicate, mod_wsgi is compiled for Python/3.5.2.

You cannot use mod_wsgi compiled for one Python version with a virtual environment created from a different Python version.

You will need to uninstall the system package for mod_wsgi and compile mod_wsgi yourself against Python 3.8.

Easiest is to use the ``pip install`` method and integrate that with the system Apache. See:

* https://pypi.org/project/mod-wsgi/

**Comment by alperencapar** [comment]
> As the Apache logs indicate, mod_wsgi is compiled for Python/3.5.2.
> 
> You cannot use mod_wsgi compiled for one Python version with a virtual environment created from a different Python version.
> 
> You will need to uninstall the system package for mod_wsgi and compile mod_wsgi yourself against Python 3.8.
> 
> Easiest is to use the `pip install` method and integrate that with the system Apache. See:
> 
> * https://pypi.org/project/mod-wsgi/

Thank you for answering 

I did remove Apache2 and libapache2-mod-wsgi-py3 however i can't install mod-wsgi and **re-installed Apache2**

**Error log:**

```
alpcusta@diricangrup:~$ python setup.py install
python: can't open file 'setup.py': [Errno 2] No such file or directory
alpcusta@diricangrup:~$ pip install mod_wsgi
Defaulting to user installation because normal site-packages is not writeable
Collecting mod_wsgi
  Using cached mod_wsgi-4.7.1.tar.gz (498 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1f2356c6/mod-wsgi_2669ca8430ab4fba99a56cf40eb329da/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1f2356c6/mod-wsgi_2669ca8430ab4fba99a56cf40eb329da/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dy1bk7hb
         cwd: /tmp/pip-install-1f2356c6/mod-wsgi_2669ca8430ab4fba99a56cf40eb329da/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1f2356c6/mod-wsgi_2669ca8430ab4fba99a56cf40eb329da/setup.py", line 165, in <module>
        raise RuntimeError('The %r command appears not to be installed or '
    RuntimeError: The 'apxs' command appears not to be installed or is not executable. Please check the list of prerequisites in the documentation for this package and install any missing Apache httpd server packages.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**I would be very happy if you could guide me in detail. I've been dealing with this problem for 4 days**

_note: i did try to run that commands as root user and sudo group user_

**Comment by GrahamDumpleton** [comment]
Read the "System Requirements" section of:

* https://pypi.org/project/mod-wsgi/

It explains that you need the development package for Apache installed if using system packages for Apache. It includes ``apxs``.

**Comment by clsteam** [comment]
@alperencapar 
you can run `sudo yum install httpd-devel –y` to install `apxs` at first.
yao,

**Comment by alperencapar** [comment]
@clsteam Thanks for answering but i couldn't fixed the problem and decided to not to use mod-wsgi. I think source of problem is Ubuntu 16.04. I believe Ubuntu 18.04 or 20.04 will fix the problem

**Comment by alperencapar** [comment]
I did upgrade Linux distribution from Ubuntu 16.04 to Ubuntu 20.04 and it works
