### ISSUE TITLE
getting exceptions import error when enter the site with WSGI with python3.7 and appache2 on ubuntu 16.04

### ISSUE THREAD

**Issue by omer-an** [GrahamDumpleton/mod_wsgi#649]
installation i done :
```
sudo apt-get --yes install python3-pip apache2 libapache2-mod-wsgi-py3 
sudo a2enmod wsgi
sudo apt install --yes python-django-common
sudo apt-get  install --yes python-django
```
i am using ubuntu 16.04 and installed python3.7 as my default using this tutorial https://stackoverflow.com/questions/41986507/unable-to-set-default-python-version-to-python3-in-ubuntu
but i get multiply import error :
```
 [wsgi:error]  mod_wsgi (pid=67194): Call to 'site.addsitedir()' failed for '/path_to_my_code/settings'.
 [wsgi:error]   mod_wsgi (pid=67194): Target WSGI script '/path_to_my_code/wsgi.py' cannot be loaded as Python module.
 [wsgi:error]   mod_wsgi (pid=67194): Exception occurred processing WSGI script '/path_to_my_code/wsgi.py'.
 [wsgi:error]   Traceback (most recent call last):
 [wsgi:error]     File "/path_to_my_code/wsgi.py", line 11, in <module>
 [wsgi:error]       from django.core.wsgi import get_wsgi_application
[wsgi:error]   ImportError: No module named 'django'
[wsgi:error] ] mod_wsgi (pid=67193): Call to 'site.addsitedir()' failed for '(null)', stopping.
 [wsgi:error] ] mod_wsgi (pid=67193): Call to 'site.addsitedir()' failed for '/path_to_my_code/settings'.
[wsgi:error] ]  mod_wsgi (pid=67193): Target WSGI script '/path_to_my_code/wsgi.py' cannot be loaded as Python module., referer: https://vm-ip/home_page
[wsgi:error] ]  mod_wsgi (pid=67193): Exception occurred processing WSGI script '/path_to_my_code/wsgi.py'., referer:https://vm-ip/home_page 
[wsgi:error] ]  Traceback (most recent call last):, referer: https://vm-ip/home_page
 [wsgi:error] ]    File "/path_to_my_code/wsgi.py", line 11, in <module>, referer: https://vm-ip/home_page
[wsgi:error] ]      from django.core.wsgi import get_wsgi_application, referer: https://vm-ip/home_page
[wsgi:error] ]  ImportError: No module named 'django', referer: https://vm-ip/home_pag
 [client ] mod_wsgi (pid=67193): Target WSGI script '/path_to_my_code/wsgi.py' cannot be loaded as Python module.
  [client ] mod_wsgi (pid=67193): Exception occurred processing WSGI script '/path_to_my_code/wsgi.py'.
  [client ] Traceback (most recent call last):
  [client ]   File "/path_to_my_code/wsgi.py", line 11, in <module>
[wsgi:error]   from django.core.wsgi import get_wsgi_application
...ImportError: No module named 'django'
```
but when i import django  from pytohn3.7 terminal i get no exceptions  
the wsgi configuration in appache2:
**command in the end of installation to load the wsgi:**
```
sudo pip install mod-wsgi
sudo a2enmod ssl
sudo a2enmod wsgi
sudo a2ensite default-ssl.conf
sudo service apache2 restart
```

**added to end of /etc/apache2/envvars:**

```
export PYTHONPATH=$BASEDIR
export PATH=$PATH:$PYTHONPATH
export PROJECT_ROOT_DIR=$PYTHONPATH
export PYTHON_EGG_CACHE=/tmp/python_egg_cache
if [ `hostname |cut -c1-3` = 'IP-' ]; then
  export COMPUTERNAME="`uname -n`"
else
  export COMPUTERNAME="IP-`uname -n`"
fi
```

`where $BASEDIR = $PYTHONPATH = $PYTHONPATH = /path_to_my_code/
`
**/etc/apache2/apache2.conf:**
```

KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5
User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}
HostnameLookups Off
ErrorLog ${APACHE_LOG_DIR}/error.log
LogLevel warn
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf

Include ports.conf

<Directory />
        Options FollowSymLinks
        AllowOverride None
        Require all denied
</Directory>

<Directory /usr/share>
        AllowOverride None
        Require all granted
</Directory>

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

AccessFileName .htaccess


<FilesMatch "^\.ht">
        Require all denied
</FilesMatch>


LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent

# Include of directories ignores editors' and dpkg's backup files,
# see README.Debian for details.

# Include generic snippets of statements
IncludeOptional conf-enabled/*.conf

# Include the virtual host configurations:
IncludeOptional sites-enabled/*.conf


```
django installed using the system Python installation of python 3.7

**Comment by GrahamDumpleton** [comment]
You have not supplied your configuration so is hard to guess. I would make the following suggestion.

* Don't use the system package for mod_wsgi that comes with Ubuntu 16.04 as it looks to be very out of date and is subject to a bug which causes problems when you add multiple paths to ``WSGIPythonPath`` or ``python-path`` option of ``WSGIDaemonProcess``. Instead remove the system package for mod_wsgi and install it yourself from source code using ``pip``. See https://pypi.org/project/mod-wsgi/

Other than that, can't suggest anything without seeing your configuration. Also indicate where your Django package is actually installed and if using a Python virtual environment, whether that is created using the system Python installation.

**Comment by omer-an** [comment]
what configuration needed to further debug the case ?

**Comment by GrahamDumpleton** [comment]
The configuration for mod_wsgi that you added to the Apache configuration file.

**Comment by omer-an** [comment]
edited and added to first comment

**Comment by GrahamDumpleton** [comment]
You supplied the main Apache configuration file and did not supply the mod_wsgi configuration.

It is going to be the ``VirtualHost`` configuration with the ```WSGI???`` directives.

**Comment by omer-an** [comment]
```
cat /etc/apache2/sites-enabled/000-default.conf
Alias /static /my_code_path/static
<Directory "/my_code_path/static">
Require all granted
</Directory>

WSGIPythonPath  /my_code_path/:/my_code_path/settings
WSGIScriptAlias / /my_code_path/wsgi.py

<Directory "/my_code_path/">
                Require all granted
</Directory>

Alias /static/admin /usr/local/lib/python3.7/dist-packages/django/contrib/admin/static/admin
<Directory "/usr/local/lib/python3.7/dist-packages/django/contrib/admin/static/admin">
    Order allow,deny
    Options Indexes
    Allow from all
    IndexOptions FancyIndexing
</Directory>
```

cat /my_code_path/wsgi.py:
```
import os
import sys
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "servicesite.settings")

path='my_code_path'

if path not in sys.path:
  sys.path.append(path)

os.environ['DJANGO_SETTINGS_MODULE'] = 'my_code_path.settings'
from django.core.wsgi import get_wsgi_application

application = get_wsgi_application()
```

**Comment by GrahamDumpleton** [comment]
As I already mentioned, don't use the system package for mod_wsgi. Install mod_wsgi yourself using ``pip``. The operating system package for version of Ubuntu you are using has a quite old version of mod_wsgi with a bug in which will cause it to fail when you have multiple paths listed in ``WSGIPythonPath`` directive as you have:

```
WSGIPythonPath  /my_code_path/:/my_code_path/settings
```

The only workaround is to add the path directories in the WSGI script file instead.

Thus instead of ``WSGIPythonPath``, at the start of the WSGI script file add:

```
import site
site.addsitedir("/my_code_path")
site.addsitedir("/my_code_path/settings")
```

**Comment by omer-an** [comment]
i am not using system package mod_wsgi i installed via pip: `sudo pip install mod-wsgi`

**Comment by GrahamDumpleton** [comment]
Are you sure you uninstalled the system package, and then added to the Apache configuration the new configuration for the ``pip`` installed version. You may need to completely stop and start Apache (not reload it), when you do this.

The error:

```
[wsgi:error] [pid 67193:tid 139927383652096] mod_wsgi (pid=67193): Call to 'site.addsitedir()' failed for '(null)', stopping.
 [wsgi:error] [pid 67193:tid 139927383652096] mod_wsgi (pid=67193): Call to 'site.addsitedir()' failed for '/path_to_my_code/settings'.
```

where is shows ``(null)`` indicates it is the old version.

What is the ``LoadModule`` lines you added to the Apache configuration for the latest version of mod_wsgi?

**Comment by omer-an** [comment]
```
    sudo a2enmod ssl
    sudo a2enmod wsgi
    sudo a2ensite default-ssl.conf
    sudo service apache2 restart
```

**Comment by omer-an** [comment]
added this lines 
```
import site
site.addsitedir("/my_code_path")
site.addsitedir("/my_code_path/settings")
```
to my wsgi.py i don't see the Call to 'site.addsitedir() exception anymore but the import exceptions are still there and home page is not loaded

**Comment by GrahamDumpleton** [comment]
If you are installing packages into the system Python, and not using a Python virtual environment, if the Django package cannot be found, one option might be that you installed Django yourself and not as system package, but in doing so you have installed it as root user where the root user had a restrictive umask, meaning that no other users on the system could actually read it.

What do you get for:

```
ls -las /usr/local/lib/python3.7/dist-packages
```

In general it is recommended to use a Python virtual environment rather than install into system Python.

* https://modwsgi.readthedocs.io/en/master/user-guides/virtual-environments.html

**Comment by omer-an** [comment]
```
# ls -las /usr/local/lib/python3.7/dist-packages
total 1680
  4 drwxrwsr-x 125 root staff   4096 Jan 26 15:24 .
  4 drwxrwsr-x  36 root staff   4096 Feb  1 09:16 ..
  4 drwxr-sr-x   3 root staff   4096 Jan 11 06:42 adal
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 adal-1.2.5.dist-info
  4 drwxr-sr-x   3 root staff   4096 Jan 11 06:42 amqp
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 amqp-2.6.1.dist-info
  4 drwxr-sr-x   7 root staff   4096 Jan 11 06:42 azure
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 azure_common-1.1.26.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 azure_core-1.9.0.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:43 azure_mgmt_compute-4.6.2.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 azure_mgmt_core-1.2.2.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:43 azure_mgmt_network-2.7.0.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 azure_mgmt_storage-16.0.0.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 azure_storage_blob-1.5.0.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 azure_storage_common-1.4.2.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 azure_storage_queue-1.4.0.dist-info
  4 drwxr-sr-x   3 root staff   4096 Jan 11 06:42 bcrypt
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 bcrypt-3.2.0.dist-info
  4 drwxr-sr-x   4 root staff   4096 Jan 11 06:42 billiard
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 billiard-3.6.3.0.dist-info
  4 drwxr-sr-x   3 root staff   4096 Jan 26 15:24 brotli
  4 drwxr-sr-x   2 root staff   4096 Jan 26 15:24 brotlipy-0.7.0.dist-info
  4 drwxr-sr-x  16 root staff   4096 Jan 11 06:42 celery
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 celery-4.3.0.dist-info
  4 drwxr-sr-x   3 root staff   4096 Jan 11 06:42 certifi
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 certifi-2020.12.5.dist-info
  4 drwxr-sr-x   5 root staff   4096 Jan 11 06:42 chardet
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 chardet-4.0.0.dist-info
  4 drwxr-sr-x   6 root staff   4096 Jan 11 06:42 dateutil
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 decorator-4.4.2.dist-info
 20 -rw-r--r--   1 root staff  17222 Jan 11 06:42 decorator.py
  **4 drwxr-sr-x  19 root staff   4096 Jan 11 06:42 django**
  **4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 Django-1.11.29.dist-info**
  4 drwxr-sr-x   4 root staff   4096 Jan 11 06:42 django_celery_beat
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 django_celery_beat-1.0.0.dist-info
  4 drwxr-sr-x   4 root staff   4096 Jan 11 06:42 et_xmlfile
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 et_xmlfile-1.0.1.dist-info
  4 drwxr-sr-x  10 root staff   4096 Jan 11 06:42 future
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 future-0.18.2.dist-info
  4 drwxr-sr-x   3 root staff   4096 Jan 26 15:24 h2
  4 drwxr-sr-x   2 root staff   4096 Jan 26 15:24 h2-2.6.2.dist-info
  4 drwxr-sr-x   3 root staff   4096 Jan 26 15:24 hpack
  4 drwxr-sr-x   2 root staff   4096 Jan 26 15:24 hpack-3.0.0.dist-info
  4 drwxr-sr-x   6 root staff   4096 Jan 26 15:24 hyper
  4 drwxr-sr-x   2 root staff   4096 Jan 26 15:24 hyper-0.8.0.dev0.dist-info
  4 drwxr-sr-x   3 root staff   4096 Jan 26 15:24 hyperframe
  4 drwxr-sr-x   2 root staff   4096 Jan 26 15:24 hyperframe-3.2.0.dist-info
  4 drwxr-sr-x   3 root staff   4096 Jan 11 06:42 idna
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 idna-2.10.dist-info
  4 drwxr-sr-x   4 root staff   4096 Jan 11 06:42 image
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 image-1.5.27.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 20 12:33 ImageHash-4.1.0.dist-info
 16 -rw-r--r--   1 root staff  12477 Jan 20 12:33 imagehash.py
  4 drwxr-sr-x   3 root staff   4096 Jan 11 06:42 importlib_metadata
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 importlib_metadata-3.4.0.dist-info
  4 drwxr-sr-x   4 root staff   4096 Jan 11 06:42 isodate
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 isodate-0.6.0.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 jdcal-1.4.1.dist-info
 16 -rw-r--r--   1 root staff  12462 Jan 11 06:42 jdcal.py
  4 drwxr-sr-x   5 root staff   4096 Jan 11 06:42 joblib
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 joblib-1.0.0.dist-info
  4 drwxr-sr-x   6 root staff   4096 Jan 11 06:42 kombu
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 kombu-4.6.11.dist-info
  4 drwxr-sr-x   4 root staff   4096 Jan 11 06:42 libfuturize
  4 drwxr-sr-x   4 root staff   4096 Jan 11 06:42 libpasteurize
  **4 drwxr-sr-x   6 root staff   4096 Jan 11 06:42 mod_wsgi**
  **4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 mod_wsgi-4.5.14.dist-info**
  4 drwxr-sr-x   6 root staff   4096 Jan 11 06:42 msrest
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 msrest-0.6.19.dist-info
  4 drwxr-sr-x   4 root staff   4096 Jan 11 06:42 msrestazure
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 msrestazure-0.6.4.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 20 15:38 mysqlclient-1.3.7.dist-info
184 -rwxr-xr-x   1 root staff 184672 Jan 20 15:38 _mysql.cpython-37m-x86_64-linux-gnu.so
  4 drwxr-sr-x   4 root staff   4096 Jan 20 15:38 MySQLdb
  4 -rw-r--r--   1 root staff   2352 Jan 20 15:38 _mysql_exceptions.py
  4 drwxr-sr-x   5 root staff   4096 Jan 11 06:42 nacl
  4 drwxr-sr-x  12 root staff   4096 Jan 20 12:24 networkx
  4 drwxr-sr-x   2 root staff   4096 Jan 20 12:24 networkx-2.2.dist-info
  4 drwxr-sr-x  17 root staff   4096 Jan 11 06:42 numpy
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 numpy-1.19.5.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 numpy.libs
  4 drwxr-sr-x   6 root staff   4096 Jan 11 06:42 oauthlib
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 oauthlib-3.1.0.dist-info
  4 drwxr-sr-x  21 root staff   4096 Jan 11 06:42 openpyxl
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 openpyxl-3.0.5.dist-info
  4 drwxr-sr-x   3 root staff   4096 Jan 11 06:42 packaging
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 packaging-20.8.dist-info
  4 drwxr-sr-x  15 root staff   4096 Jan 11 06:42 pandas
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 pandas-1.2.0.dist-info
  4 drwxr-sr-x   3 root staff   4096 Jan 11 06:42 paramiko
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 paramiko-2.7.2.dist-info
  4 drwxr-sr-x   7 root staff   4096 Jan 11 06:42 past
  4 drwxr-sr-x   3 root staff   4096 Jan 20 15:33 PIL
  4 drwxr-sr-x   2 root staff   4096 Jan 20 15:33 Pillow-8.1.0.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 20 15:33 Pillow.libs
  4 drwxr-sr-x   4 root staff   4096 Jan 11 06:42 pint
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 Pint-0.16.1.dist-info
  4 drwxr-sr-x   5 root staff   4096 Jan 20 12:19 pip
  4 drwxr-sr-x   2 root staff   4096 Jan 20 12:19 pip-20.3.3.dist-info
  4 drwxr-sr-x   4 root staff   4096 Jan 20 12:24 psutil
  4 drwxr-sr-x   2 root staff   4096 Jan 20 12:24 psutil-5.4.5.dist-info
  4 drwxr-sr-x   2 root staff   4096 Feb  1 09:16 __pycache__
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 PyNaCl-1.4.0.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 pyodbc-4.0.30.dist-info
580 -rwxr-xr-x   1 root staff 591904 Jan 11 06:42 pyodbc.cpython-37m-x86_64-linux-gnu.so
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 pyparsing-2.4.7.dist-info
268 -rw-r--r--   1 root staff 273365 Jan 11 06:42 pyparsing.py
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 python_dateutil-2.8.1.dist-info
  4 drwxr-sr-x   4 root staff   4096 Jan 11 06:42 pytz
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 pytz-2020.5.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 PyWavelets-1.1.1.dist-info
  4 drwxr-sr-x   6 root staff   4096 Jan 11 06:42 pywt
  4 drwxr-sr-x   3 root staff   4096 Jan 11 06:42 requests
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 requests-2.25.1.dist-info
  4 drwxr-sr-x   4 root staff   4096 Jan 11 06:42 requests_oauthlib
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 requests_oauthlib-1.3.0.dist-info
  4 drwxr-sr-x   3 root staff   4096 Jan 26 15:24 rfc3986
  4 drwxr-sr-x   2 root staff   4096 Jan 26 15:24 rfc3986-1.4.0.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 scikit_learn-0.21.0.dist-info
  4 drwxr-sr-x  22 root staff   4096 Jan 11 06:42 scipy
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 scipy-1.6.0.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 scipy.libs
  4 drwxr-sr-x  33 root staff   4096 Jan 11 06:42 sklearn
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 sklearn-0.0.dist-info
  4 drwxr-sr-x  14 root staff   4096 Jan 11 06:42 sqlalchemy
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 SQLAlchemy-1.3.22.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 typing_extensions-3.7.4.3.dist-info
 84 -rw-r--r--   1 root staff  83727 Jan 11 06:42 typing_extensions.py
  4 drwxr-sr-x   6 root staff   4096 Jan 11 06:42 urllib3
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 urllib3-1.26.2.dist-info
  4 drwxr-sr-x   4 root staff   4096 Jan 11 06:42 vine
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 vine-1.3.0.dist-info
  4 drwxr-sr-x   2 root staff   4096 Jan 11 06:42 zipp-3.4.0.dist-info
  8 -rw-r--r--   1 root staff   8089 Jan 11 06:42 zipp.py

```

**Comment by GrahamDumpleton** [comment]
Only thing I can suggest at this point is to add at the start of your WSGI script file:

```
import sys
print("sys.version", sys.version)
print("sys.prefix", sys.prefix)
print("sys.path", sys.path)
```

Find what this outputs in the Apache error log file when application is loaded on a request.

This is to verify what version of Python is used, where it is located, and what Python search path is being used.

Either the system Python isn't actually being used, and what is used isn't searching in the correct locations, or another possibility is AppArmor on Ubuntu is setup in a way that prevents the Apache process from accessing those locations.

**Comment by omer-an** [comment]
```

sys.prefix /usr/local
[wsgi:error] [pid 20417:tid 139860971022080] 
sys.path ['/my_code_path/', '/my_code_path/settings', '/usr/local/lib/python37.zip', '/usr/local/lib/python3.7', '/usr/local/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/site-packages', '/my_code_path/settings', '/my_code_path', '/my_code_path/settings.py']

```

**Comment by GrahamDumpleton** [comment]
For mod_wsgi you are not using the system Python package, but appear to be using a Python version which is installed under ``/usr/local``. The Django package however appears to be installed with the system Python package, as only the system Python package looks in ``/usr/local/lib/python3.7/dist-packages``. A separate Python installation will not look in that location.

Can you confirm you have a separate Python installation under ``/usr/local``?

At this point I would suggest you start using a Python virtual environment, install all the Python modules you need in that and setup mod_wsgi to use that Python virtual environment. Don't rely on any Python packages which have been installed with the system Python package.

* https://modwsgi.readthedocs.io/en/master/user-guides/virtual-environments.html

I would also highly recommend you use mod_wsgi daemon and not use embedded mode.

**Comment by omer-an** [comment]
i have both system and `/usr/local` but i would like to use only system interpreter in wsgi and in django

**Comment by GrahamDumpleton** [comment]
Try setting:

```
WSGIPythonHome /usr
```

Even that may not work because it looks like your system shared library search path is setup such that shared libraries are found from ``/usr/local/lib`` before system lib directory. Only forcing which installation to use may not be enough if wrong shared library is being linked.

What do you get if you run:

```
unset LD_LIBRARY_PATH
ldd mod_wsgi.so
```

in the directory where the ``mod_wsgi.so`` file is located.

If you didn't copy the ``mod_wsgi.so`` file into the Apache installation, then run:

```
mod_wsgi-express module-location
```

to work out where it is located, and use the path that outputs as argument to ``ldd``.

**Comment by omer-an** [comment]
```
ldd /usr/lib/apache2/modules/mod_wsgi.so
        linux-vdso.so.1 =>  (0x00007ffdb053b000)
        libpython3.7m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0 (0x00007ff6492ad000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff649090000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff648cc6000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007ff648a9d000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff648883000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff64867f000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007ff64847c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff648173000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff649c27000)

```

`mod_wsgi-express module-location
`
return 
`/home/ubuntu/.local/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so
`
```

ldd /home/ubuntu/.local/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so
        linux-vdso.so.1 =>  (0x00007fff5bea3000)
        libpython3.7m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0 (0x00007ff901917000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff9016fa000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff901330000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007ff901107000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff900eed000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff900ce9000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007ff900ae6000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff9007dd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff902293000)

```

**Comment by GrahamDumpleton** [comment]
Try setting:

```
WSGIPythonHome /usr
```

as already mentioned then.

**Comment by omer-an** [comment]
tried `set WSGIPythonHome /usr` no change

**Comment by GrahamDumpleton** [comment]
All I can reason is that the Ubuntu Python could well be broken when used in embedded systems.

Add to ``WSGIPythonPath`` directive:

```
/usr/local/lib/python3.7/dist-packages
```

You really should be using a virtual environment as I said already. It is bad practice to install packages direct into system Python installation as ``pip`` installed packages can interfere with operating system required Python packages that are packaged by the system.

Ignore that it is talking about docker as same applies to normal system, but read:

* http://blog.dscpl.com.au/2016/01/python-virtual-environments-and-docker.html

as to why virtual environments is preferred.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue or gave up.
