### ISSUE TITLE
Not possible to send email using mod_wsgi - prefork module issue?

### ISSUE THREAD

**Issue by JianDk** [GrahamDumpleton/mod_wsgi#664]
I have a Django project deployed in production using mod_wsgi. In development it was possible for user to fill out a form followed by submitting it to the backend. An email will then be generated and sent. When I tested it in development everything was fine and I received the email. However in production there is something wrong and when I inspect the error log I can't trace to the root cause of this error. My error logs is as below

```
[Sat Mar 20 18:36:52.693566 2021] [authz_core:error] [pid 63623:tid 140495391864576] [client 66.249.69.150:50390] AH01630: client denied by server configuration: /etc/wsgi-port-80/htdocs/cgi-bin
[Sat Mar 20 18:46:20.822928 2021] [authz_core:error] [pid 63623:tid 140495391598336] [client 66.249.75.187:51831] AH01630: client denied by server configuration: /etc/wsgi-port-80/htdocs/cgi-bin
[Sat Mar 20 18:49:18.121736 2021] [authz_core:error] [pid 63600:tid 140495390799616] [client 66.249.77.27:61325] AH01630: client denied by server configuration: /etc/wsgi-port-80/htdocs/cgi-bin
[Sat Mar 20 18:49:25.616719 2021] [wsgi:error] [pid 63599:tid 140495337584384] [remote 52.175.223.195:7872] Not Found: /wp-includes/js/wp-emoji-release.min.js
[Sat Mar 20 18:50:25.165286 2021] [wsgi:error] [pid 63599:tid 140494956918528] Exception in thread Thread-7:
[Sat Mar 20 18:50:25.165357 2021] [wsgi:error] [pid 63599:tid 140494956918528] Traceback (most recent call last):
[Sat Mar 20 18:50:25.165373 2021] [wsgi:error] [pid 63599:tid 140494956918528]   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[Sat Mar 20 18:50:25.165832 2021] [wsgi:error] [pid 63599:tid 140494956918528]     self.run()
[Sat Mar 20 18:50:25.165847 2021] [wsgi:error] [pid 63599:tid 140494956918528]   File "/usr/lib/python3.8/threading.py", line 870, in run
[Sat Mar 20 18:50:25.166139 2021] [wsgi:error] [pid 63599:tid 140494956918528]     self._target(*self._args, **self._kwargs)
[Sat Mar 20 18:50:25.166153 2021] [wsgi:error] [pid 63599:tid 140494956918528]   File "/home/jianwu/HD_website/website/website/Modules/emailMessage.py", line 71, in sendEmailNow_Thread
[Sat Mar 20 18:50:25.166267 2021] [wsgi:error] [pid 63599:tid 140494956918528]     smtpObj = smtplib.SMTP(host=cred['email']['host'], port = cred['email']['port'])
[Sat Mar 20 18:50:25.166280 2021] [wsgi:error] [pid 63599:tid 140494956918528]   File "/usr/lib/python3.8/smtplib.py", line 253, in __init__
[Sat Mar 20 18:50:25.166486 2021] [wsgi:error] [pid 63599:tid 140494956918528]     (code, msg) = self.connect(host, port)
[Sat Mar 20 18:50:25.166499 2021] [wsgi:error] [pid 63599:tid 140494956918528]   File "/usr/lib/python3.8/smtplib.py", line 339, in connect
[Sat Mar 20 18:50:25.166655 2021] [wsgi:error] [pid 63599:tid 140494956918528]     self.sock = self._get_socket(host, port, self.timeout)
[Sat Mar 20 18:50:25.166667 2021] [wsgi:error] [pid 63599:tid 140494956918528]   File "/usr/lib/python3.8/smtplib.py", line 308, in _get_socket
[Sat Mar 20 18:50:25.166813 2021] [wsgi:error] [pid 63599:tid 140494956918528]     return socket.create_connection((host, port), timeout,
[Sat Mar 20 18:50:25.166829 2021] [wsgi:error] [pid 63599:tid 140494956918528]   File "/usr/lib/python3.8/socket.py", line 808, in create_connection
[Sat Mar 20 18:50:25.167192 2021] [wsgi:error] [pid 63599:tid 140494956918528]     raise err
[Sat Mar 20 18:50:25.167209 2021] [wsgi:error] [pid 63599:tid 140494956918528]   File "/usr/lib/python3.8/socket.py", line 796, in create_connection
[Sat Mar 20 18:50:25.167516 2021] [wsgi:error] [pid 63599:tid 140494956918528]     sock.connect(sa)
[Sat Mar 20 18:50:25.167551 2021] [wsgi:error] [pid 63599:tid 140494956918528] TimeoutError: [Errno 110] Connection timed out

```

Right now I am configuring my mod_wsgi server using the bash script as below

```
#!/bin/sh

#Configuration on how to start the server
python manage.py runmodwsgi \
--server-root /etc/wsgi-port-80 \
--user www-data --group www-data \
--port 80 --setup-only \
--https-only \
--https-port 443 \
--ssl-certificate-file "/etc/letsencrypt/live/www.dimsum.dk/cert.pem" \
--ssl-certificate-key-file "/etc/letsencrypt/live/www.dimsum.dk/privkey.pem" \
--server-name 'www.dimsum.dk'

#Starting the server
sudo /etc/wsgi-port-80/apachectl stop
sudo /etc/wsgi-port-80/apachectl start
```

I am wondering if the reason why my backend is not able to send email in production setting is due to the below lines in the error log reported above? Also what does this line means and has it something to do with my incorrect setting of mod_wsgi or apache?

`AH01630: client denied by server configuration: /etc/wsgi-port-80/htdocs/cgi-bin`

**Comment by GrahamDumpleton** [comment]
Answered in discussion at:

* https://groups.google.com/g/modwsgi/c/WpLU0t4oFEQ/m/qEC1MvHvBAAJ

Repeating here. The error:

```
TimeoutError: [Errno 110] Connection timed out
```

implies that your production machine doesn't have the appropriate network access to the email server it is trying to use to send email.

**Comment by GrahamDumpleton** [comment]
Closing as no further response and assumed information provided was sufficient to solve any issue.
