### ISSUE TITLE
 ModuleNotFoundError: No module named 'django' - Apache VirtualHost

### ISSUE THREAD

**Issue by NickWinston123** [GrahamDumpleton/mod_wsgi#755]
I have followed solutions and posted several stackoverflow post but could not fix my issue. I have seen some of these problems here fixed, @GrahamDumpleton could you please help me? I spent a lot of time working on this project and have spent the majority of this week trying to solve this with no success.

I am using Apache and `Ubuntu 18.04.4 LTS` and I am using a venv for my application using `python 3.8.12` using python3 -m venv. My global default python3 --version is also 3.8.12 but I was using 3.6 before upgrading. I am also using `Django version 4.0.1`

I am using a Virtualhost because I have another website running but it is using wordpress. (and a few other websites configured but not used).

I installed mod_wsgi by git cloning the source from here and configuring to my venvs python then running `sudo make`, `sudo make install` 

**VirtualHost** settings in `/etc/apache2/apache2.conf`:
```
WSGIApplicationGroup %{GLOBAL}
WSGIPythonHome /home/john/djangoapp/pricewatcher/venv/
WSGIPythonPath /home/john/djangoapp/pricewatcher/backend/
<VirtualHost *:80>
  ServerAlias www.d8pricecheck.tk

  Alias /static/ /home/john/djangoapp/pricewatcher/backend/static/
  <Directory /home/john/djangoapp/pricewatcher/backend/static>
    Require all granted
  </Directory>
  
  WSGIScriptAlias / /home/john/djangoapp/pricewatcher/backend/core/wsgi.py

  <Directory /home/john/djangoapp/pricewatcher/backend/core>
    <Files wsgi.py>
      Require all granted
    </Files>
  </Directory>
 WSGIDaemonProcess www.d8pricecheck.com python-path=/home/john/djangoapp/pricewatcher/backend python-home=/home/john/djangoapp/pricewatcher/venv/
 WSGIProcessGroup www.d8pricecheck.com
</VirtualHost>
```

**wsgi.py** file in `/backend/core/wsgi.py`
```

import os, sys
python_home = '/home/john/djangoapp/pricewatcher/venv'

import site

python_version = '.'.join(map(str, sys.version_info[:2]))
site_packages = python_home + '/lib/python%s/site-packages' % python_version

site.addsitedir(site_packages)

# add the hellodjango project path into the sys.path
sys.path.append('/home/john/djangoapp/pricewatcher/backend/')

sys.path.append('/home/john/djangoapp/pricewatcher/backend/core/')

# add the virtualenv site-packages path to the sys.path
sys.path.append('/home/john/djangoapp/pricewatcher/venv/lib/python3.8/site-packages')


from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')

application = get_wsgi_application()
```

**pip freeze** from within my venv:
```
APScheduler==3.8.1
asgiref==3.5.0
backports.zoneinfo==0.2.1
beautifulsoup4==4.10.0
bs4==0.0.1
certifi==2021.10.8
charset-normalizer==2.0.10
colorama==0.4.4
commonmark==0.9.1
deepdiff==5.7.0
discord-webhook==0.14.0
Django==4.0.1
django-cors-headers==3.11.0
djangorestframework==3.13.1
idna==3.3
lxml==4.7.1
ordered-set==4.0.2
prettytable==3.0.0
psycopg2-binary==2.9.3
Pygments==2.11.2
pytz==2021.3
pytz-deprecation-shim==0.1.0.post0
requests==2.27.1
rich==11.1.0
six==1.16.0
soupsieve==2.3.1
sqlparse==0.4.2
tzdata==2021.5
tzlocal==4.1
urllib3==1.26.8
wcwidth==0.2.5
whitenoise==5.3.0
```

**Full Apache error log** from restarting and visiting the website:
```
[Wed Feb 02 14:25:17.561969 2022] [mpm_prefork:notice] [pid 13161] AH00171: Graceful restart requested, doing restart
[Wed Feb 02 14:25:17.676208 2022] [ssl:warn] [pid 13161] AH01916: Init: (nextgearserver.hsd1.ga.comcast.net:443) You configured HTTP(80) on the standard HTTPS(443) port!
[Wed Feb 02 14:25:17.677122 2022] [mpm_prefork:notice] [pid 13161] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1g mod_wsgi/4.9.1.dev1 Python/3.8 configured -- resuming normal operations
[Wed Feb 02 14:25:17.677140 2022] [core:notice] [pid 13161] AH00094: Command line: '/usr/sbin/apache2'
[Wed Feb 02 14:25:23.328848 2022] [wsgi:error] [pid 14655] [remote 108.162.238.183:33688] mod_wsgi (pid=14655): Failed to exec Python script file '/home/john/djangoapp/pricewatcher/backend/core/wsgi.py'.
[Wed Feb 02 14:25:23.328892 2022] [wsgi:error] [pid 14655] [remote 108.162.238.183:33688] mod_wsgi (pid=14655): Exception occurred processing WSGI script '/home/john/djangoapp/pricewatcher/backend/core/wsgi.py'.
[Wed Feb 02 14:25:23.333152 2022] [wsgi:error] [pid 14655] [remote 108.162.238.183:33688] Traceback (most recent call last):
[Wed Feb 02 14:25:23.333175 2022] [wsgi:error] [pid 14655] [remote 108.162.238.183:33688]   File "/home/john/djangoapp/pricewatcher/backend/core/wsgi.py", line 30, in <module>
[Wed Feb 02 14:25:23.333181 2022] [wsgi:error] [pid 14655] [remote 108.162.238.183:33688]     from django.core.wsgi import get_wsgi_application
[Wed Feb 02 14:25:23.333196 2022] [wsgi:error] [pid 14655] [remote 108.162.238.183:33688] ModuleNotFoundError: No module named 'django'
[Wed Feb 02 14:25:23.538803 2022] [wsgi:error] [pid 14655] [remote 162.158.187.159:15872] mod_wsgi (pid=14655): Failed to exec Python script file '/home/john/djangoapp/pricewatcher/backend/core/wsgi.py'.
[Wed Feb 02 14:25:23.538919 2022] [wsgi:error] [pid 14655] [remote 162.158.187.159:15872] mod_wsgi (pid=14655): Exception occurred processing WSGI script '/home/john/djangoapp/pricewatcher/backend/core/wsgi.py'.
[Wed Feb 02 14:25:23.539122 2022] [wsgi:error] [pid 14655] [remote 162.158.187.159:15872] Traceback (most recent call last):
[Wed Feb 02 14:25:23.539194 2022] [wsgi:error] [pid 14655] [remote 162.158.187.159:15872]   File "/home/john/djangoapp/pricewatcher/backend/core/wsgi.py", line 30, in <module>
[Wed Feb 02 14:25:23.539215 2022] [wsgi:error] [pid 14655] [remote 162.158.187.159:15872]     from django.core.wsgi import get_wsgi_application
[Wed Feb 02 14:25:23.539263 2022] [wsgi:error] [pid 14655] [remote 162.158.187.159:15872] ModuleNotFoundError: No module named 'django'
```

Django parent folder permissions using `ls -l`:
```
(.venv) john@nextgearserver:~$ ls -l djangoapp/
total 4
drwxrwxrwx 9 john john 4096 Feb  1 16:11 pricewatcher
```

Doing python3 in my venv:
import sys
print(sys.version)
print(sys.prefix)
```
Python 3.8.12 (default, Jan 15 2022, 18:39:47)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.version)
3.8.12 (default, Jan 15 2022, 18:39:47)
[GCC 7.5.0]
>>> print(sys.prefix)
/home/john/djangoapp/pricewatcher/.venv
```
Doing python3 outside my venv:
import sys
print(sys.version)
print(sys.prefix)
```
Python 3.8.12 (default, Jan 15 2022, 18:39:47)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.version)
3.8.12 (default, Jan 15 2022, 18:39:47)
[GCC 7.5.0]
>>> print(sys.prefix)
/usr
```
(.venv) john@nextgearserver:~$ ls -las /home/john/djangoapp/pricewatcher/venv/lib/python3.8/site-packa
ges/
```
total 36
4 drwxrwxrwx 8 john john 4096 Feb  1 16:11 .
4 drwxrwxrwx 3 john john 4096 Feb  1 16:11 ..
4 drwxrwxrwx 3 john john 4096 Feb  1 16:11 _distutils_hack
4 -rwxrwxrwx 1 john john  152 Feb  1 16:11 distutils-precedence.pth
4 drwxrwxrwx 5 john john 4096 Feb  1 16:11 pip
4 drwxrwxrwx 2 john john 4096 Feb  1 16:11 pip-21.1.1.dist-info
4 drwxrwxrwx 6 john john 4096 Feb  1 16:11 pkg_resources
4 drwxrwxrwx 7 john john 4096 Feb  1 16:11 setuptools
4 drwxrwxrwx 2 john john 4096 Feb  1 16:11 setuptools-56.0.0.dist-info
```

**Comment by NickWinston123** [comment]
After doing the sys.prefix in my venv i noticed the .venv I deleted and recreated the venv with the right name and I am no longer getting this error 

I am getting this error now but I think it is a permission problem?
```
[Wed Feb 02 14:45:12.750077 2022] [mpm_prefork:notice] [pid 13161] AH00171: Graceful restart requested, doing restart
[Wed Feb 02 14:45:12.895672 2022] [ssl:warn] [pid 13161] AH01916: Init: (nextgearserver.hsd1.ga.comcast.net:443) You configured HTTP(80) on the standard HTTPS(443) port!
[Wed Feb 02 14:45:12.896633 2022] [mpm_prefork:notice] [pid 13161] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1g mod_wsgi/4.9.1.dev1 Python/3.8 configured -- resuming normal operations
[Wed Feb 02 14:45:12.896652 2022] [core:notice] [pid 13161] AH00094: Command line: '/usr/sbin/apache2'
[Wed Feb 02 19:45:34.796210 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102] mod_wsgi (pid=15073): Failed to exec Python script file '/home/john/djangoapp/pricewatcher/backend/core/wsgi.py'.
[Wed Feb 02 19:45:34.796271 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102] mod_wsgi (pid=15073): Exception occurred processing WSGI script '/home/john/djangoapp/pricewatcher/backend/core/wsgi.py'.
[Wed Feb 02 19:45:34.797104 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102] Traceback (most recent call last):
[Wed Feb 02 19:45:34.797145 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/home/john/djangoapp/pricewatcher/backend/core/wsgi.py", line 34, in <module>
[Wed Feb 02 19:45:34.797151 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     application = get_wsgi_application()
[Wed Feb 02 19:45:34.797158 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/home/john/djangoapp/pricewatcher/venv/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Wed Feb 02 19:45:34.797163 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     django.setup(set_prefix=False)
[Wed Feb 02 19:45:34.797169 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/home/john/djangoapp/pricewatcher/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
[Wed Feb 02 19:45:34.797174 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     apps.populate(settings.INSTALLED_APPS)
[Wed Feb 02 19:45:34.797180 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/home/john/djangoapp/pricewatcher/venv/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
[Wed Feb 02 19:45:34.797184 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     app_config.ready()
[Wed Feb 02 19:45:34.797190 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/home/john/djangoapp/pricewatcher/backend/apps/pricewatcher/apps.py", line 12, in ready
[Wed Feb 02 19:45:34.797194 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     from .src import watcher_launcher
[Wed Feb 02 19:45:34.797200 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/home/john/djangoapp/pricewatcher/backend/apps/pricewatcher/src/watcher_launcher.py", line 19, in <module>
[Wed Feb 02 19:45:34.797205 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     logger = logger_client.logger_client("PriceWatcher",'logs')
[Wed Feb 02 19:45:34.797211 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/home/john/djangoapp/pricewatcher/backend/apps/Utilities/logger_client.py", line 22, in __init__
[Wed Feb 02 19:45:34.797227 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     os.makedirs(self.BASE_COLLECTIONS_FOLDER, exist_ok=False)
[Wed Feb 02 19:45:34.797234 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/usr/lib/python3.8/os.py", line 223, in makedirs
[Wed Feb 02 19:45:34.797238 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     mkdir(name, mode)
[Wed Feb 02 19:45:34.797253 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102] PermissionError: [Errno 13] Permission denied: 'logs'
[Wed Feb 02 19:45:35.023147 2022] [wsgi:error] [pid 15073] [remote 162.158.187.159:52646] mod_wsgi (pid=15073): Failed to exec Python script file '/home/john/djangoapp/pricewatcher/backend/core/wsgi.py'.
[Wed Feb 02 19:45:35.023287 2022] [wsgi:error] [pid 15073] [remote 162.158.187.159:52646] mod_wsgi (pid=15073): Exception occurred processing WSGI script '/home/john/djangoapp/pricewatcher/backend/core/wsgi.py'.
[Wed Feb 02 19:45:35.023600 2022] [wsgi:error] [pid 15073] [remote 162.158.187.159:52646] Traceback (most recent call last):
[Wed Feb 02 19:45:35.023709 2022] [wsgi:error] [pid 15073] [remote 162.158.187.159:52646]   File "/home/john/djangoapp/pricewatcher/backend/core/wsgi.py", line 34, in <module>
[Wed Feb 02 19:45:35.023729 2022] [wsgi:error] [pid 15073] [remote 162.158.187.159:52646]     application = get_wsgi_application()
[Wed Feb 02 19:45:35.023753 2022] [wsgi:error] [pid 15073] [remote 162.158.187.159:52646]   File "/home/john/djangoapp/pricewatcher/venv/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Wed Feb 02 19:45:35.023769 2022] [wsgi:error] [pid 15073] [remote 162.158.187.159:52646]     django.setup(set_prefix=False)
[Wed Feb 02 19:45:35.023791 2022] [wsgi:error] [pid 15073] [remote 162.158.187.159:52646]   File "/home/john/djangoapp/pricewatcher/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
[Wed Feb 02 19:45:35.023806 2022] [wsgi:error] [pid 15073] [remote 162.158.187.159:52646]     apps.populate(settings.INSTALLED_APPS)
[Wed Feb 02 19:45:35.023827 2022] [wsgi:error] [pid 15073] [remote 162.158.187.159:52646]   File "/home/john/djangoapp/pricewatcher/venv/lib/python3.8/site-packages/django/apps/registry.py", line 83, in populate
[Wed Feb 02 19:45:35.023843 2022] [wsgi:error] [pid 15073] [remote 162.158.187.159:52646]     raise RuntimeError("populate() isn't reentrant")
[Wed Feb 02 19:45:35.023915 2022] [wsgi:error] [pid 15073] [remote 162.158.187.159:52646] RuntimeError: populate() isn't reentrant
```

**Comment by NickWinston123** [comment]
After adding a user to www-data and setting up permissions I don't think I am getting that error anymore unless it is way up in the logs. I am now getting an error about no module named `'encodings'`?

```
Current thread 0x00007fb225a80bc0 (most recent call first):
<no Python frame>
Python path configuration:
  PYTHONHOME = '/home/noah/djangoapp/pricewatcher/venv/'
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/home/noah/djangoapp/pricewatcher/venv'
  sys.base_exec_prefix = '/home/noah/djangoapp/pricewatcher/venv'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/home/noah/djangoapp/pricewatcher/venv'
  sys.exec_prefix = '/home/noah/djangoapp/pricewatcher/venv'
  sys.path = [
    '/home/noah/djangoapp/pricewatcher/venv/lib/python38.zip',
    '/home/noah/djangoapp/pricewatcher/venv/lib/python3.8',
    '/home/noah/djangoapp/pricewatcher/venv/lib/python3.8/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
```

**Comment by GrahamDumpleton** [comment]
Looks like you have really broken permissions on files under your home directory. It is really bad practice to be blindly running `chmod ugo+rwx` as you appear to have done. It is going to be hard to guess what you have broken since you have playing with permissions so much.

When code runs under Apache it runs as the Apache user. For some Linux distros the home directory is not accessible to other users and thus placing your project under your home directory will not work. It thus can be better to place your deployed project files under a directory outside of your home directory.

First thing to check for trying to host from under your home directory is the permissions on your home directory, then all directories down to the root of your project code. Thus what do you get for:

```
ls -lasd /home/john
ls -lasd /home/john/djangoapp
ls -lasd /home/john/djangoapp/pricewatcher
ls -lasd /home/john/djangoapp/pricewatcher/venv
```

**Comment by NickWinston123** [comment]
Thanks for replying! I think I ran a few chmod and messed it up when thinking apache did not have permissions. I did not know that about the home folder. I tried to move it to /var/www/(pricewatcher/backend/core) and edited the virtual host and wsgi.py but I am still getting the same error as before. I did make the project on another computer so tomorrow I will scp it back over into /var/www/ and try again 

If I run those on where I moved it, I get this:
(venv) john@nextgearserver:/var/www$ ls -lasd /var/www/
`4 drwxr-xr-x 14 root root 4096 Feb  2 21:38 /var/www/`
(venv) john@nextgearserver:/var/www$ ls -lasd /var/www/pricewatcher/
`4 drwxrw---- 10 john varwwwusers 4096 Feb  2 17:28 /var/www/pricewatcher/`
(venv) john@nextgearserver:/var/www$ ls -lasd /var/www/pricewatcher/venv
`4 drwxrwxr-x 5 john john 4096 Feb  2 17:28 /var/www/pricewatcher/venv`

```

**Comment by GrahamDumpleton** [comment]
The directory `/var/www/pricewatcher/` needs to be:

```
drwxrwxr-x
```

as well. Which in update to comment you now say was tried.

Since could also be uncertainties around what mod_wsgi you are using is compiled against, I would suggest you use the `pip install` method to build mod_wsgi.

* https://pypi.org/project/mod-wsgi/

Install this into the Python virtual environment. Don't use root to create the Python virtual environment, nor for installing packages into the Python virtual environment. Use your own user. Ensure you have a `umask` like 022 and not 020.

Then undo main Apache configuration for using mod_wsgi installed into the Apache modules directory and instead insert in Apache configuration the output of running `mod_wsgi-express module-config` as explained in the PyPi page.

Make sure you are doing a complete `stop` and `start` of Apache service and not `reload` or `restart` when switching which mod_wsgi to use.

Finally, test with a WSGI hello world first rather than your application WSGI application. Your Django WSGI script file is wrong for other reasons, so lets just get a hello world working.

**Comment by NickWinston123** [comment]
Oh my gosh, my server is actually running! If I comment out the init in logger_client.py where it creates the directory if it does not exist and comment out the writing to a file part in def log(message), I am able to get it to launch!!

Is there a way I can fix the permission issue so I could reenable it again? After its run for a little bit it should start populating the database so I will be able to test that soon

**Comment by GrahamDumpleton** [comment]
The message:

```
[Wed Feb 02 19:45:34.796210 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102] mod_wsgi (pid=15073): Failed to exec Python script file '/home/john/djangoapp/pricewatcher/backend/core/wsgi.py'.
[Wed Feb 02 19:45:34.796271 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102] mod_wsgi (pid=15073): Exception occurred processing WSGI script '/home/john/djangoapp/pricewatcher/backend/core/wsgi.py'.
[Wed Feb 02 19:45:34.797104 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102] Traceback (most recent call last):
[Wed Feb 02 19:45:34.797145 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/home/john/djangoapp/pricewatcher/backend/core/wsgi.py", line 34, in <module>
[Wed Feb 02 19:45:34.797151 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     application = get_wsgi_application()
[Wed Feb 02 19:45:34.797158 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/home/john/djangoapp/pricewatcher/venv/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Wed Feb 02 19:45:34.797163 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     django.setup(set_prefix=False)
[Wed Feb 02 19:45:34.797169 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/home/john/djangoapp/pricewatcher/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
[Wed Feb 02 19:45:34.797174 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     apps.populate(settings.INSTALLED_APPS)
[Wed Feb 02 19:45:34.797180 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/home/john/djangoapp/pricewatcher/venv/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
[Wed Feb 02 19:45:34.797184 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     app_config.ready()
[Wed Feb 02 19:45:34.797190 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/home/john/djangoapp/pricewatcher/backend/apps/pricewatcher/apps.py", line 12, in ready
[Wed Feb 02 19:45:34.797194 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     from .src import watcher_launcher
[Wed Feb 02 19:45:34.797200 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/home/john/djangoapp/pricewatcher/backend/apps/pricewatcher/src/watcher_launcher.py", line 19, in <module>
[Wed Feb 02 19:45:34.797205 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     logger = logger_client.logger_client("PriceWatcher",'logs')
[Wed Feb 02 19:45:34.797211 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/home/john/djangoapp/pricewatcher/backend/apps/Utilities/logger_client.py", line 22, in __init__
[Wed Feb 02 19:45:34.797227 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     os.makedirs(self.BASE_COLLECTIONS_FOLDER, exist_ok=False)
[Wed Feb 02 19:45:34.797234 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]   File "/usr/lib/python3.8/os.py", line 223, in makedirs
[Wed Feb 02 19:45:34.797238 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102]     mkdir(name, mode)
[Wed Feb 02 19:45:34.797253 2022] [wsgi:error] [pid 15073] [remote 108.162.237.40:40102] PermissionError: [Errno 13] Permission denied: 'logs'
```

is because you are trying to use a relative path name. You can't do that and must calculate an absolute path name.

I noticed that as an issue way back, but then all the other permissions got mucked up and so had to deal with them first.

See docs which explains this sort of issue.

* https://modwsgi.readthedocs.io/en/master/user-guides/application-issues.html#application-working-directory

**Comment by NickWinston123** [comment]
Thank you, I will make that change. I appreciate the help, I am happy to get it working!
