### ISSUE TITLE
Windows Apache Server running Django/Python throws django.http.request.UnreadablePostError:  Apche/mod_wsgi request data read error....

### ISSUE THREAD

**Issue by jamestatham2019** [GrahamDumpleton/mod_wsgi#764]
### The Apache server (2.4.46) running Python 3.9, is throwing the following error:

 OSError: Apache/mod_wsgi request data read error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.  .\r
 \r
 The above exception was the direct cause of the following exception:\r
 \r
 Traceback (most recent call last):\r
   File "c:\\program files\\python39\\lib\\site-packages\\django\\http\\request.py", line 300, in body\r
     self._body = self.read()\r
   File "c:\\program files\\python39\\lib\\site-packages\\django\\http\\request.py", line 357, in read\r
    raise UnreadablePostError(*e.args) from e\r
 django.http.request.UnreadablePostError: Apache/mod_wsgi request data read error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.  .\r
 \r
 The above exception was the direct cause of the following exception:\r
 \r
 Traceback (most recent call last):\r
   File "c:\\program files\\python39\\lib\\site-packages\\django\\core\\handlers\\exception.py", line 34, in inner\r
     response = get_response(request)\r
  File "c:\\program files\\python39\\lib\\site-packages\\django\\core\\handlers\\base.py", line 115, in _get_response\r
     response = self.process_exception_by_middleware(e, request)\r
  File "c:\\program files\\python39\\lib\\site-packages\\django\\core\\handlers\\base.py", line 113, in _get_response\r
     response = wrapped_callback(request, *callback_args, **callback_kwargs)\r
   File "c:\\program files\\python39\\lib\\site-packages\\django\\views\\decorators\\csrf.py", line 54, in wrapped_view\r
     return view_func(*args, **kwargs)\r
  File "C:/raptor/AdminSrvr\\raptor\\apis.py", line 125, in device\r
     **if request.POST.get('guid','UNKNOWN'):**\r
   File "c:\\program files\\python39\\lib\\site-packages\\django\\core\\handlers\\wsgi.py", line 102, in _get_post\r
     self._load_post_and_files()\r
   File "c:\\program files\\python39\\lib\\site-packages\\django\\http\\request.py", line 335, in _load_post_and_files\r
     self._post, self._files = QueryDict(self.body, encoding=self._encoding), MultiValueDict()\r
   File "c:\\program files\\python39\\lib\\site-packages\\django\\http\\request.py", line 302, in body\r
     raise UnreadablePostError(*e.args) from e\r
 django.http.request.UnreadablePostError: Apache/mod_wsgi request data read error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.  .\r
 INFO:django.request:OK: /device/\r
 Traceback (most recent call last):\r
   File "c:\\program files\\python39\\lib\\site-packages\\django\\http\\request.py", line 355, in read\r
     return self._stream.read(*args, **kwargs)\r
   File "c:\\program files\\python39\\lib\\site-packages\\django\\core\\handlers\\wsgi.py", line 34, in read\r
     result = self.buffer + self._read_limited()\r
   File "c:\\program files\\python39\\lib\\site-packages\\django\\core\\handlers\\wsgi.py", line 28, in _read_limited\r
     result = self.stream.read(size)\r

This line in bold, IS NOT in error and the server is not timing out processing the connection(s)...

I have noticed that this problem crops up much more often in an MPM configuration...

Reading between the lines, it seems to me that *maybe* my mod_wsgi version isn't built for my python (3.9) version?!?

**Comment by GrahamDumpleton** [comment]
In general this would indicate that the HTTP client wasn't sending all the request content it promised to send based on the request content size in the request, or is disconnecting before sending all the request content. What is the HTTP client, a mobile app?

**Comment by jamestatham2019** [comment]
Thanks for responding!  The client is a Windows or Mac agent running on a desktop or laptop...
