### ISSUE TITLE
Exception occurred processing WSGI script - FileNotFoundError: [Errno 2] No such file or directory: '/logs/debug.log'

### ISSUE THREAD

**Issue by monkeyden** [GrahamDumpleton/mod_wsgi#852]
Getting the following exception when making a request to my Django application.

 mod_wsgi (pid=2502072): Exception occurred processing WSGI script '/opt/django_project/main/viewerauth/wsgi.py'.
Traceback (most recent call last):
File "/usr/lib/python3.8/logging/config.py", line 563, in configure
  handler = self.configure_handler(handlers[name])
File "/usr/lib/python3.8/logging/config.py", line 744, in configure_handler
  result = factory(**kwargs)
File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
  StreamHandler.__init__(self, self._open())
File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
  return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/logs/debug.log'

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/opt/user/django_project/main/wsgi.py", line 24, in <module>
  application = get_wsgi_application()
File "/opt/django_project/main/venv/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
  django.setup(set_prefix=False)
File "/opt/django_project/main/venv/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
  configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
File "/opt/django_project/main/venv/lib/python3.8/site-packages/django/utils/log.py", line 76, in configure_logging
  logging_config_func(logging_settings)
File "/usr/lib/python3.8/logging/config.py", line 808, in dictConfig
  dictConfigClass(config).configure()
File "/usr/lib/python3.8/logging/config.py", line 570, in configure
  raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'

WSGI appears to be trying to load a logging config that uses '/logs/debug.log'.  Where is this path coming from?  My settings.py logging config logs to an entirely different file.

**Comment by monkeyden** [comment]
No sooner than I posted this did I recognize my own error.  I made a change to my app installer that dropped the deployment in a different location.  This broke my sys.path.append paths in wsgi.py, thus the logging config in settings.py was never found.  Changing those to the new path fixed my issue.
