### ISSUE TITLE
Setting up mod_wsgi to use Python Virtual Environment: cannot find modules.

### ISSUE THREAD

**Issue by techmaticsnz** [GrahamDumpleton/mod_wsgi#855]
I am running Manjaro Linux version 23.0
Running Python 3.11.5

I installed mod_wsgi version 4.9.4 using command
```
pamac build mod_wsgi
```
phpinfo() reports that this is the apache version
```
Apache/2.4.57 (Unix) PHP/8.2.10 mod_wsgi/4.9.4 Python/3.11
```

Configured an apache virtual environment with the following configuration:
```
<VirtualHost 127.0.0.1:80>
        ServerName  flask-app.com
        ServerAlias www.flask-app.com
        ServerAdmin webmaster@localhost
        DocumentRoot /srv/flask-app
 
        WSGIDaemonProcess flaskapp threads=5
        WSGIScriptAlias / /srv/flask-app/flaskapp.wsgi
        WSGIApplicationGroup %{GLOBAL}
        <Directory /srv/flask-app>
             Require all granted
        </Directory>
 
        ErrorLog /var/log/httpd/flaskapp-error.log
        CustomLog /var/log/httpd/flaskapp-access.log combined
</VirtualHost>
```
flaskapp.wsgi
```

import sys 
import logging

sys.path.append('/srv/flask-app')
sys.path.append('/path/to/venv/python3.11/site-packages')

#setup logging
logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)

print(sys.path)

#import and run the flask app
from app import app as application
```
I installed flask into the virtual environment and when it runs the following error happens.
```
[Fri Sep 15 11:51:58.510427 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998] mod_wsgi (pid=4594): Failed to exec Python script file '/srv/flask-app/flaskapp.wsgi'.
[Fri Sep 15 11:51:58.510468 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998] mod_wsgi (pid=4594): Exception occurred processing WSGI script '/srv/flask-app/flaskapp.wsgi'.
[Fri Sep 15 11:51:58.510616 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998] Traceback (most recent call last):
[Fri Sep 15 11:51:58.512430 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998]   File "/srv/flask-app/flaskapp.wsgi", line 11, in <module>
[Fri Sep 15 11:51:58.512443 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998]     from app import app as application
[Fri Sep 15 11:51:58.512450 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998]   File "/srv/flask-app/app.py", line 1, in <module>
[Fri Sep 15 11:51:58.512453 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998]     from flask import Flask
[Fri Sep 15 11:51:58.512464 2023] [wsgi:error] [pid 4594] [remote 127.0.0.1:52998] ModuleNotFoundError: No module named 'flask'
```
Installing flask to system python makes it work but i'd like for the installation to work with a virtual environment.
I've tried using python-home property to the WSGIDaemonProcess and it timesout.
I added TimeOut 600 to httpd.conf. It just sits there without response.
I've also tried using WSGIPythonHome and WSGIPythonPath to httpd.conf with same results.

This is my first time setting up this kind of installation so any help would be appreciated.
Thanks in advance!

**Comment by techmaticsnz** [comment]
Sorry wrong user. I'll log onto my personal account.

**Comment by GrahamDumpleton** [comment]
You are missing the `WSGIProcessGroup` directive to tell it to use that daemon process group.

That is wrong but in itself shouldn't have caused the problem.

Instead of using:

```
sys.path.append('/srv/flask-app')
sys.path.append('/path/to/venv/python3.11/site-packages')
```

you are better off using:

```
        WSGIDaemonProcess flaskapp threads=5 python-home=/path/to/venv python-path=/srv/flask-app
        WSGIProcessGroup flaskapp
        WSGIApplicationGroup %{GLOBAL}

        WSGIScriptAlias / /srv/flask-app/flaskapp.wsgi

```
