### ISSUE TITLE
Getting error if target.endswith('/') and path != '/': while trying to run python manage.py runmodwsgi

### ISSUE THREAD

**Issue by rehbarkhan** [GrahamDumpleton/mod_wsgi#871]
I am using mod_wsgi with django 4.2 and while running the command : 

```
python manage.py runmodwsgi --reload-on-changes --host 0.0.0.0 \ 
--user core_app --group core_app --port 8080 --log-to-terminal 
```

got error below error 

```
web       | core_db
web       | Operations to perform:
web       |   Apply all migrations: admin, auth, contenttypes, sessions
web       | Running migrations:
web       |   No migrations to apply.
web       | core_db
web       |
web       | 0 static files copied to '/core/static', 125 unmodified.
web       | core_db
web       | Successfully ran command.
web       | Server URL         : http://localhost:8080/
web       | Server Root        : /tmp/mod_wsgi-localhost:8080:1000
web       | Server Conf        : /tmp/mod_wsgi-localhost:8080:1000/httpd.conf
web       | Error Log File     : /dev/stderr (warn)
web       | Operating Mode     : daemon
web       | Request Capacity   : 5 (1 process * 5 threads)
web       | Request Timeout    : 60 (seconds)
web       | Startup Timeout    : 15 (seconds)
web       | Queue Backlog      : 100 (connections)
web       | Queue Timeout      : 45 (seconds)
web       | Server Capacity    : 20 (event/worker), 20 (prefork)
web       | Server Backlog     : 500 (connections)
web       | Locale Setting     : en_US.UTF-8
web       | Traceback (most recent call last):
web       |   File "/core/manage.py", line 22, in <module>
web       |     main()
web       |   File "/core/manage.py", line 18, in main
web       |     execute_from_command_line(sys.argv)
web       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
web       |     utility.execute()
web       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
web       |     self.fetch_command(subcommand).run_from_argv(self.argv)
web       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
web       |     self.execute(*args, **cmd_options)
web       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
web       |     output = self.handle(*args, **options)
web       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web       |   File "/usr/local/lib/python3.11/site-packages/mod_wsgi/server/management/commands/runmodwsgi.py", line 134, in handle
web       |     options = mod_wsgi.server._cmd_setup_server(
web       |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web       |   File "/usr/local/lib/python3.11/site-packages/mod_wsgi/server/__init__.py", line 3626, in _cmd_setup_server
web       |     generate_apache_config(options)
web       |   File "/usr/local/lib/python3.11/site-packages/mod_wsgi/server/__init__.py", line 1092, in generate_apache_config
web       |     if target.endswith('/') and path != '/':
web       |        ^^^^^^^^^^^^^^^
web       | AttributeError: 'PosixPath' object has no attribute 'endswith'
```

django stting is 
project_dir/poject_dir/settigns/base.py
as my setting is in one extra level I have changed the base_dir 
BASE_DIR = Path(__file__).resolve().parent.parent.parent
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static/'
# MEDIA_URL = not required as it will containt user specific data.
MEDIA_ROOT = BASE_DIR / 'media/'

kindly help on resolving this issue.

**Comment by rehbarkhan** [comment]
Oh never mind got the fix 
just has to use os.path.join(BASE_DIR,'static')
